### ISSUE TITLE
Regression in KSampler (inspire) after latest update?

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Inspire-Pack#100]
There seems to be some sort of regression after 92cd5108c49f1071f2f95e005dc7e04b72abe768.

First Inspire sampler works fine, but when the result is forwarded to second, it goes crazy on the output.

Here is an example:
![after](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/d1ed06f1-cf43-41d4-92f0-e90bdfd12e9b)

If I revert the above commit, it looks good again:
![before](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/72d9433f-a2e6-436a-9dcd-f059bfec83bd)

Recreating the node didn't help.

**Comment by LuLmaster69** [comment]
The same thing is happening during inpainting for me.

**Comment by josemerinom** [comment]
update both Impact Pack and Inspire Pack?

**Comment by alexopus** [comment]
> update both Impact Pack and Inspire Pack

Both are latest.

**Comment by LuLmaster69** [comment]
My results also have become non-deterministic. The previously used seeds give different results if you reload them in a new session of ComfyUI.
The default Ksampler in ComfyUI does not exhibit this behavior.

**Comment by ltdrdata** [comment]
I need to review it.
Sorry for the situation.

**Comment by wardensc2** [comment]
I also get the same result, I though denoise of Ksampler (inspire) is broken, somehow it's always is 1

**Comment by ltdrdata** [comment]
This is fixed. But update Impact Pack as well.
Impact Pack's sampler has a bug which is 3m is operate as 2m.
