### ISSUE TITLE
The Denoise in Ksampler is out of control.

### ISSUE THREAD

**Issue by K-O-N-B** [ltdrdata/ComfyUI-Inspire-Pack#101]
whatever I choose 0.01 or 1, the result seemingly always be 1.

origianl img:
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/152141077/3434f3b4-a2bb-492d-9e7d-d05ee1a3f0f0)

denoise 0.01:
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/152141077/204cf2d3-cc22-4b17-9b55-5584df267eaf)

denoise 0.1:
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/152141077/1003ecdf-e0a8-4492-b687-75a78073e4a9)

denoise 1:
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/152141077/d5eded1c-3981-4944-864f-4461b5e4da0c)

**Comment by K-O-N-B** [comment]
this is img2img workflow.

**Comment by ltdrdata** [comment]
This is fixed last night.
Update Inspire Pack and Impact Pack.
