### ISSUE TITLE
module 'impact.core' has no attribute 'SCHEDULERS'

### ISSUE THREAD

**Issue by cardenluo** [ltdrdata/ComfyUI-Inspire-Pack#102]
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/133877069/7aa2af63-4bbd-4aa0-815e-bc68389d442f)

**Comment by ltdrdata** [comment]
Update ComfyUI-Impact-Pack to latest version.

**Comment by cardenluo** [comment]
yes , OK now ,thanks
