### ISSUE TITLE
Issue with KSampler (inspire)

### ISSUE THREAD

**Issue by masaint** [ltdrdata/ComfyUI-Inspire-Pack#104]
Getting the following error when using the included Ksampler node in any capacity whatsoever -

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/135912013/26fa04f5-e586-4a27-b974-608cb4f90e76)

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/135912013/ac55ff23-9d45-4f1a-a2c6-c9c60aaedb65)

**Comment by ltdrdata** [comment]
oops...
I forgot to pushing updated Impact Pack.

Update Impact Pack.

**Comment by masaint** [comment]
ah no problem, thanks for checking :)
