### ISSUE TITLE
Error with "unzip prompt" with a "Load Prompts From File" node

### ISSUE THREAD

**Issue by holycause** [ltdrdata/ComfyUI-Inspire-Pack#111]
Hi, 
I am getting the following error with some of the prompts files:

Error occurred when executing UnzipPrompt //Inspire:

UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'

File "C:\Users\XXX\tools\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\XXX\tools\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\XXX\tools\ComfyUI\execution.py", line 69, in map_node_over_list
results.append(getattr(obj, func)())

**Comment by holycause** [comment]
I thought that the issue was coming from those nodes but it isn't.
sorry about that

**Comment by holycause** [comment]
it is actually from that unzip node.
sorry for the confusion.

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by ltdrdata** [comment]
> I have a similar workflow, but it doesn't happen all the time. this one is giving me the error. ![image](https://private-user-images.githubusercontent.com/1366662/334095742-d7fbd98a-b298-49ff-bd0f-1e74d857573b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjEwMDIsIm5iZiI6MTcxNjgyMDcwMiwicGF0aCI6Ii8xMzY2NjYyLzMzNDA5NTc0Mi1kN2ZiZDk4YS1iMjk4LTQ5ZmYtYmQwZi0xZTc0ZDg1NzU3M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMTQzODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE3YTMzNGM3MjI4NTE4YWIzNTBjZTdlZjZkMDg1ZDRkZjU4NWU0ZmE2YzFhNTVlMWE2MTMwYWQ1MjBmNTU5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PeyfVHceb_NekoQ_fL7gTJxa2Ow5Jx7_W-3n5nrBqXw)

That is not a workflow just a node.

**Comment by holycause** [comment]
additional information
I am using a python script to write my text files.
It seems that this might be the issue as if I copy paste the content into a new file, that new files doesn't get any errors.

**Comment by holycause** [comment]
I can confirm that this was the issue.
I made a few changes to my code to make sure I have the correct encoding and that fixed the issue
