### ISSUE TITLE
Missing AYS sampler scheduler 

### ISSUE THREAD

**Issue by wandrzej** [ltdrdata/ComfyUI-Inspire-Pack#116]
Someone shared a workflow that was using the Inspire Ksampler, with a AYS SDXL scheduler 

I have the ComfyUI-Inspire-Pack (V0.75.2). No errors during loading related to this custom node

Left is the node from the workflow, right is a new node and I don't see this option in selection. What's interesting is that I can still run the sampler with the settings on the right. 

Anyway I wonder if inspire didn't fully install, and the library didn't get loaded, or some other custom node is overwriting those settings. Would be great if it was actually running AYS especially that the implementation with the external scheduler has a minimum step count hard coded to 10. 

<img width="740" alt="image" src="https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/26924000/49c82618-695f-416e-b976-8167d7522459">

**Comment by ltdrdata** [comment]
refresh browser.

**Comment by LCloiseau** [comment]
did not help

**Comment by ltdrdata** [comment]
> did not help

Make sure you are using **KSampler (Inspire)** and not the core **KSampler**.

**Comment by LCloiseau** [comment]
I did. Everything is up to date and loaded without fails. Only thing I can think of is I use confyui and A1111 (mostly for the civitai helper), so I had to redirect comfyui to you the same path (edit the extra_model_paths.yaml) but I don't see anything in there that mentions schedulers.
![inspire](https://github.com/user-attachments/assets/11734fe3-b4e9-4dca-a53c-91e125f72f83)

**Comment by ltdrdata** [comment]
> I did. Everything is up to date and loaded without fails. Only thing I can think of is I use confyui and A1111 (mostly for the civitai helper), so I had to redirect comfyui to you the same path (edit the extra_model_paths.yaml) but I don't see anything in there that mentions schedulers. ![inspire](https://private-user-images.githubusercontent.com/152874706/396125954-11734fe3-b4e9-4dca-a53c-91e125f72f83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTg1MTAsIm5iZiI6MTczNDM1ODIxMCwicGF0aCI6Ii8xNTI4NzQ3MDYvMzk2MTI1OTU0LTExNzM0ZmUzLWI0ZTktNGRjYS1hNTNjLTkxZTEyNWY3MmY4My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNDEwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDU2ZjZlNzc0MjQ5MzRhZWIwYTk2ZjliMmMyNGM1MjdhNWZlNGE0MTZlNDJlNGY4NzgzNTI2YjhlNzFjZjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c1pIJ8rKU9zQXFlUrldaJuXI0Y0y-Lp4bgAfsV9c0xE)

Please upload the `comfyui.log`.

**Comment by LCloiseau** [comment]
[comfyui.log](https://github.com/user-attachments/files/18151615/comfyui.log)
I also tried to convert widget to input for the scheduler and add a scheduler selector (impact) node, and this one shows AYS SDXL, but it won't hook up to the ksampler. 
![scheduler](https://github.com/user-attachments/assets/3d38d402-fe2a-44df-8899-1594d430f8cb)

**Comment by ltdrdata** [comment]
> [comfyui.log](https://github.com/user-attachments/files/18151615/comfyui.log) I also tried to convert widget to input for the scheduler and add a scheduler selector (impact) node, and this one shows AYS SDXL, but it won't hook up to the ksampler. ![scheduler](https://private-user-images.githubusercontent.com/152874706/396131878-3d38d402-fe2a-44df-8899-1594d430f8cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDA0MDcsIm5iZiI6MTczNDQwMDEwNywicGF0aCI6Ii8xNTI4NzQ3MDYvMzk2MTMxODc4LTNkMzhkNDAyLWZlMmEtNDRkZi04ODk5LTE1OTRkNDMwZjhjYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwMTQ4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTVkOGE3ZDBlOTBkZjU0NmYwZjhjYzE3MTJiYzcwMmEwZTFmMmMwOWE0MjAyNWEwMTY4MmExNGEwOTI5YjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nIIS83A8QqWJ7ur9o5cfiRlJSzXcglyYJWnHfTUfowo)

Your Inspire Pack is not updated. 
It is very outdated version.

Latest Inpire Pack version is 1.9.

**Comment by LCloiseau** [comment]
That did it ! Thank you so much !
