### ISSUE TITLE
 (IMPORT FAILED) ComfyUI Inspire Pack

### ISSUE THREAD

**Issue by BellZwei** [ltdrdata/ComfyUI-Inspire-Pack#117]
![Screenshot 2024-06-27 001152](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/154002537/8adc354d-6d9d-4273-968e-cc0046a9db59)

I attempted to use the fix button as well as a manual installation, but neither method was successful.

**Comment by ltdrdata** [comment]
You have to check the terminal log.

**Comment by BellZwei** [comment]
I installed ComfyUI Impact Pack and it got fixed!

**Comment by DJLegends1011** [comment]
> ComfyUI Impact Pack

thank you for the solution had same issue!!
