### ISSUE TITLE
[Feature resquest] Let user specify path for prompt files

### ISSUE THREAD

**Issue by brayevalerien** [ltdrdata/ComfyUI-Inspire-Pack#120]
Currently, the following nodes only allow the user to load files and directories from the `ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/prompts` directory:
- Load Prompts from Dir
- Load Prompts from File
- Load Single Prompt from File

This is not very user-friendly, especially when sharing the workflow to other (and inexperienced) people, since they need to dive into the folder structure of ComfyUI to put the file containing the prompts in the required location.

Instead of forcing the user choose from a fixed list of path (files/dir) contained in the global prompt directory, I suggest replacing the input by a string, that will let the user specify a custom path.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/c16f165d-d327-4df9-aada-eadb04506d4b)

`text_data_opt` input is added.
If `text_data_opt` is connected, it uses the input text instead of reading from a file.
