### ISSUE TITLE
Slow LoRA Loader with Block Weight

### ISSUE THREAD

**Issue by ai-waifu-life** [ltdrdata/ComfyUI-Inspire-Pack#121]
Hello! After running updates for ComfyUI and no other changes to any other drivers or requirements that I am aware of, the LoRA loaders are extremely slow. Usually it'll be slow for the first run, like a second or two per loader, but then blast through them for following generations. Now it is taking several seconds per loader and it does not seem to cache for following generations, so every one has to go through that. I replaced them with the standard loaders and those work normally, so seems to be something with Inspire's loaders. I set highvram and that didn't make any difference. Running on a 4070 Super and this is my first time encountering an issue like this.

**Comment by ltdrdata** [comment]
I'll check this later.

**Comment by ai-waifu-life** [comment]
> I'll check this later.

Just checking if you've had a sec to take a look. Lemme know if you need anything from my end!

**Comment by ltdrdata** [comment]
![lbw-simple](https://github.com/user-attachments/assets/3c997814-1669-4d8a-9c85-3c1b35a2bf85)

Is this issue also being reproduced in this workflow? In my tests, while there is a slowdown when model patches are applied block by block compared to the default LoRA, even this process is instantaneous, so it's not to the extent that it would be problematic.

**Comment by ai-waifu-life** [comment]
> Is this issue also being reproduced in this workflow? In my tests, while there is a slowdown when model patches are applied block by block compared to the default LoRA, even this process is instantaneous, so it's not to the extent that it would be problematic.

I noticed that in that you have the seed set to fixed. If no changes are made to the LORA Loader at all, then it is quick after the first run. If I randomize the seed, like I always have, then it will treat it like a first process every time.

**Comment by ltdrdata** [comment]
> > Is this issue also being reproduced in this workflow? In my tests, while there is a slowdown when model patches are applied block by block compared to the default LoRA, even this process is instantaneous, so it's not to the extent that it would be problematic.
> 
> I noticed that in that you have the seed set to fixed. If no changes are made to the LORA Loader at all, then it is quick after the first run. If I randomize the seed, like I always have, then it will treat it like a first process every time.

It is correct to always re-execute when randomizing the seed. This is because the patch weights applied to the model change. That seed is a feature to randomize the 'r' when it is used in block weight.

**Comment by ai-waifu-life** [comment]
> It is correct to always re-execute when randomizing the seed. This is because the patch weights applied to the model change. That seed is a feature to randomize the 'r' when it is used in block weight.

Oh! Wait, so that could mean my workflow wasn't working correctly previously? 😂 Well that's great to know lol.
Appreciate your time on this!
