### ISSUE TITLE
Latest version doesn't load in ComfyUI.

### ISSUE THREAD

**Issue by donlee1** [ltdrdata/ComfyUI-Inspire-Pack#123]
The latest version (fresh install from ComfyUI image to the latest version of Inspire Pack) doesn't load on ComfyUI.
I switched to the commit "git checkout 9c57899" and it loads properly. There must be something wrong with the latest version. Thank you!

**Comment by ltdrdata** [comment]
What are the error messages displayed in the terminal log when starting ComfyUI?

**Comment by albamuth** [comment]
I updated earlier today and got an error that the weight type was not one of the right kinds. selecting the weight type fixed it.

Incidentally, where can I find a rundown on the different weight types and their usages?

**Comment by donlee1** [comment]
> What are the error messages displayed in the terminal log when starting ComfyUI?

I get this log:
==> /var/log/supervisor/comfyui.log <==
### Loading: ComfyUI-Manager (V2.46.3)
### ComfyUI Revision: 2129 [719fb2c8] *DETACHED | Released on '2024-04-14'
### Loading: ComfyUI-Inspire-Pack (V0.82)

==> /var/log/supervisor/caddy.log <==

And the workflow that requires the Inspire Pack displays this message on ComfyUI:
"When loading the graph, the following node types were not found:
* KSamplerAdvanced //Inspire
* ConcatConditioningsWithMultiplier //Inspire
Nodes that have failed to load will show as red on the graph."

It seems like latest ComfyUI version doesn't provide the reason for a node not loading, so I'm not sure which part of the Inspire custom node is causing this issue.
FYI this happens to a fresh install of the latest ComfyUI (AI-dock).

Manually downgrading the Inspire pack with "git checkout 9c57899" and restarting ComfyUI successfully loads the custom node.

**Comment by ltdrdata** [comment]
> > What are the error messages displayed in the terminal log when starting ComfyUI?
> 
> I get this log: ==> /var/log/supervisor/comfyui.log <==
> 
> ### Loading: ComfyUI-Manager (V2.46.3)
> ### ComfyUI Revision: 2129 [719fb2c8] *DETACHED | Released on '2024-04-14'
> ### Loading: ComfyUI-Inspire-Pack (V0.82)
> ==> /var/log/supervisor/caddy.log <==
> 
> And the workflow that requires the Inspire Pack displays this message on ComfyUI: "When loading the graph, the following node types were not found:
> 
> * KSamplerAdvanced //Inspire
> * ConcatConditioningsWithMultiplier //Inspire
>   Nodes that have failed to load will show as red on the graph."
> 
> It seems like latest ComfyUI version doesn't provide the reason for a node not loading, so I'm not sure which part of the Inspire custom node is causing this issue. FYI this happens to a fresh install of the latest ComfyUI (AI-dock).
> 
> Manually downgrading the Inspire pack with "git checkout [9c57899](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/commit/9c578996b0d97be4611961f6ce8aac9491940cc0)" and restarting ComfyUI successfully loads the custom node.

Is the `Inspire Pack` loaded successfully without import error?

```
   0.0 seconds: /mnt/teratera/git/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
```
