### ISSUE TITLE
KeyError: 'workflow' only when using API

### ISSUE THREAD

**Issue by jelling** [ltdrdata/ComfyUI-Inspire-Pack#125]
I'm getting an error from Inspire when using the API even though my workflow does not use any Inspire nodes:

```
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 683, in trigger_on_prompt
    json_data = handler(json_data)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/inspire/inspire_server.py", line 365, in onprompt
    populate_wildcards(json_data)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/inspire/inspire_server.py", line 334, in populate_wildcards
    for node in json_data['extra_data']['extra_pnginfo']['workflow']['nodes']:
KeyError: 'workflow'
```

The issue seems to happen because of [this section](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/cadf604de528be62e4fbb1e3d12c51c98f20f50b/inspire/inspire_server.py#L333):

```
        if 'extra_data' in json_data and 'extra_pnginfo' in json_data['extra_data']:
            for node in json_data['extra_data']['extra_pnginfo']['workflow']['nodes']:
```

The relevant section of the sent workflow:

```
  "extra_data": { "extra_pnginfo": {} }
```

So it looks like it just doesn't handle cases where `extra_pnginfo` is empty. 

(Why it's empty, I don't know, as the workflow was created by someone else.)

**Comment by ltdrdata** [comment]
That is a feature to display the populated prompt from wildcards in the workflow on the browser, and it's unnecessary in the API. I've applied a patch to prevent any issues.
