### ISSUE TITLE
Ksampler (inspire) 

### ISSUE THREAD

**Issue by Creative-comfyUI** [ltdrdata/ComfyUI-Inspire-Pack#126]
Hello, 

I am preparing a long tutorial about how to manage image in comfyUI and I am using Ksampler (inspire) 

I need your confirmation. The variation is applied to the prompt not to the base noise is it correct? 

Here is what I have done. I write a prompt and use sampler euler without variation. As expected, I have the same 3 images.   Then I muted the prompt with the zero condition. This time Euler doesn't give the same 3 images as it should, there is a slight variation. How do you explain this? 

Thank you.

**Comment by ltdrdata** [comment]
The `seed` generates noise to fill the latent space through a sequence of random values.
The `variation_seed` generates a second noise.
The `variation_strength` is the ratio that mixes the noise generated by the base seed and the noise generated by the variation_seed.

When `variation_strength` is 0, it's equivalent to applying only the `seed`. When `variation_strength` is 1.0, it's equivalent to applying only the `variation_seed`.

**Comment by Creative-comfyUI** [comment]
Thanks for the information 

In general strength is radom noise?   Why in general when strength is zero we can not inject noise ?

Here is the case 

I took an image and used it as a prompt with clipvision condition strength 0 and I tried to inject noise using inspire noise injection. Instead of having an enriched image, I have noise instead of image. Why is this?

**Comment by ltdrdata** [comment]
> Thanks for the information
> 
> In general strength is radom noise? Why in general when strength is zero we can not inject noise ?
> 
> Here is the case
> 
> I took an image and used it as a prompt with clipvision condition strength 0 and I tried to inject noise using inspire noise injection. Instead of having an enriched image, I have noise instead of image. Why is this?

When `variation_strength` is set to 0, it means, as the name suggests, that no variation should be applied.
The strength of clipvision conditioning is a feature that is completely unrelated to `KSampler (Inspire)`.

**Comment by Creative-comfyUI** [comment]
Maybe I'm not expressing myself well, I was talking about Inspire RandomNoise Inspire 

![workflow-14](https://github.com/user-attachments/assets/535ff22b-1003-4bbe-adb6-b219b05771e7)

It will be good if we can evaluate the strength of the noise. This means that every time we use strength, we should have a seed for that strength and other parameters that can be used as a reference later when we want to add the same type of noise to an image.

**Comment by ltdrdata** [comment]
> Maybe I'm not expressing myself well, I was talking about Inspire RandomNoise Inspire
> 
> ![workflow-15](https://private-user-images.githubusercontent.com/166729777/350708822-c5812ad2-ed33-4910-840d-72c664b1f3db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTk2MjksIm5iZiI6MTcyMTUxOTMyOSwicGF0aCI6Ii8xNjY3Mjk3NzcvMzUwNzA4ODIyLWM1ODEyYWQyLWVkMzMtNDkxMC04NDBkLTcyYzY2NGIxZjNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQyMzQ4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTE0MWRkMzRmOWUwODkxYjkxN2U4ODNjZDY0Zjc0MmJjZDAxZDAxMjBkNDdlNGRmNjQ5NDNmYmNmNWMzMTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dg6BNBEN63kJRX5HJa7NwxvBN20EliK02YcgaeJtyOk)
> 
> It that case you see you have for the unClippingConditionning Strength and noise_augmentation as it was two think different.
> 
> It will be good if we cn evaluate the strength of the noise. This means that every time we use strength, we should have a seed for that strength and other parameters that can be used as a reference later when we want to add the same type of noise to an image.

That is an invalid usage of that Noise node.

That `RandomNoise` is a node that replaces the built-in `RandomNoise` node, allowing you to use functions similar to `KSampler (Inspire)` when using `SamplerCustom` or `SamplerCustomAdvanced` nodes.

This is valid usage of Noise node.

![randomnoise](https://github.com/user-attachments/assets/7c0f8dc6-da94-4b56-b006-4933d0498152)

If you pass the LATENT generated through AddNoise to a regular KSampler node, it will be eliminated by the noise that the KSampler or KSamplerAdvanced node adds on its own.
