### ISSUE TITLE
Request for adding lora block weights

### ISSUE THREAD

**Issue by ytoaa** [ltdrdata/ComfyUI-Inspire-Pack#127]
https://github.com/hako-mikan/sd-webui-lora-block-weight?tab=readme-ov-file#start-stop-step
The above features allow you to choose from what level of lora you want to start and end.

**Comment by ltdrdata** [comment]
If what you want is to control through the prompt instead of splitting the workflow for control, you can use this node.

https://github.com/asagi4/comfyui-prompt-control#scheduling-syntax

This node supports LBW functionality through Inspire Pack, so it can be applied simultaneously.
