### ISSUE TITLE
Lora Loader with Block Weight Category Filter

### ISSUE THREAD

**Issue by ai-waifu-life** [ltdrdata/ComfyUI-Inspire-Pack#128]
Hello! What is the point of this section? I cannot find any information online about it other than "This optional parameter allows you to filter the application of the Lora model based on specific categories, providing an additional layer of customization." But it does not describe anywhere how to actually utilize it or add categories to it. Currently it's just 'Any'. Thanks!

**Comment by ltdrdata** [comment]
When you select a subdirectory in the category filter, the list of LoRAs displayed when choosing a LoRA in lora_name is limited. It's a convenience feature.
Those categories are automatically generated based on the directory names.

**Comment by ai-waifu-life** [comment]
@ltdrdata I just thought of a way this could work and didn't know how to mention it and am not a coder, so don't want to make a pull request.
Could you implement a new node that is a switch of the "If ANY return A else B"  and have the A/B switched to output and then have a single input alongside the boolean? It would allow a true/false toggle that could be used to allow users to create an if/else scenario to automatically bypass or repath flows.
