### ISSUE TITLE
Concat Conditionings with Multiplier adds duplicate multipliers and results in error

### ISSUE THREAD

**Issue by GeorgeCiesinski** [ltdrdata/ComfyUI-Inspire-Pack#129]
Whenever I reopen ComfyUI or load a workflow from an image, the **Concat Conditionings with Multiplier** node adds a bunch of extra multipliers. This results in one of two behaviours, one of which results in an error.

1) A bunch of extra multipliers are added after the multipliers in use. Since the four conditionings I am using match the four multiplier names, the duplicates don't cause an error.

![image](https://github.com/user-attachments/assets/7f286dc6-753e-49dd-bb4a-ad2be65818f1)

2) [ Results in Error ] Extra multipliers are added, but the first few multipliers which are in use are changed. 

Sometimes this occurs when I restart ComfyUI or load a workflow, but other times this occurs when I attempt to fix the node attachments from the first behaviour by reattaching nodes.

![image](https://github.com/user-attachments/assets/1cc4fc28-c89e-4cea-a8cf-f2342121b3cd)

When I queue'd a job, it resulted in the following error: 

```
Error occurred when executing ConcatConditioningsWithMultiplier //Inspire:

'multiplier3'

  File "D:\AI-Image-Generation\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Image-Generation\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Image-Generation\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Image-Generation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\conditioning_nodes.py", line 52, in doit
    multiplier = float(kwargs[mkey])
                       ~~~~~~^^^^^^
```

# Additional Info

- When I initially add this node to my workflow and set it up, it works without issues. 
- I noticed the warning `[Inspire Pack] IPAdapterPlus is not installed.` in my console, but I cannot find any information about this or how to fix it. I am not sure if this may have something to do with this issue, or if it is unrelated.
- I noticed that only **Concat Conditionings with Multiplier** with three or more attached nodes are affected. I also have **Concat Conditionings with Multiplier** nodes with only two attached nodes that are unaffected and load properly.
- If the duplicate multipliers have a different value, the lowest multiplier value will be used

**Comment by ltdrdata** [comment]
This is fixed.
