### ISSUE TITLE
dood your image load from dir node is trying to load txt files cmon...

### ISSUE THREAD

**Issue by 2blackbar** [ltdrdata/ComfyUI-Inspire-Pack#13]
fix this ,its easy and it is logical error on your side

 `def load_images(self, directory: str, image_load_cap: int = 0, start_index: int = 0):
    if not os.path.isdir(directory):
        raise FileNotFoundError(f"Directory '{directory} cannot be found.'")
    dir_files = os.listdir(directory)
    if len(dir_files) == 0:
        raise FileNotFoundError(f"No files in directory '{directory}'.")

    # Filter files by extension
    valid_extensions = ['.jpg', '.jpeg', '.png']
    dir_files = [f for f in dir_files if any(f.lower().endswith(ext) for ext in valid_extensions)]

    dir_files = sorted(dir_files)
    dir_files = [os.path.join(directory, x) for x in dir_files]

    # start at start_index
    dir_files = dir_files[start_index:]`

**Comment by ltdrdata** [comment]
thank you
