### ISSUE TITLE
Regional Conditioning By Color Mask - Animatediff Support !

### ISSUE THREAD

**Issue by jerrydavos** [ltdrdata/ComfyUI-Inspire-Pack#130]
Hey, 

I wanted to know if I'm doing something wrong or the regional prompt is not supported yet for Animatediff. 

Recently I've got some good results with minimum prompt bleeding in single Image Generation.... wanted to get similar results in with animatediff but it is producing glitched with AD

Quick Example: 

Below is a simple animatediff workflow, which uses the 2 Regional Prompt nodes for character and background based on a mask. 

![workflow (2)](https://github.com/user-attachments/assets/c9b80a82-bbe2-4f9e-9046-a9f148e57ca0)
[Animatediff Regional Prompts.json](https://github.com/user-attachments/files/16347289/Animatediff.Regional.Prompts.json)
Here Is the mask used: 
![New Project](https://github.com/user-attachments/assets/074a6ae9-aadd-4b60-a096-24e099cc252b)

So when it works as normal, not using the regional conditioning nodes, the result is this: 
![AnimateDiff_00005](https://github.com/user-attachments/assets/40771a57-dec7-4d93-ba21-15c324267a1b)

when using with the Regional condition nodes, The result is all bugged: 
![AnimateDiff_00006](https://github.com/user-attachments/assets/45d3485c-92a9-4749-8d6c-7dbadf605421)

The above is just a simple example to showcase the problem.... I used a [more complicated](https://openart.ai/workflows/jerrydavos/v30-bg-changer-v2/lCgtgqjT0sq97xsNq0f6) workflow which uses 2 controlnets.... the results were same glitched outputs.

You are putting a lot of efforts in making these nodes, really appreciate it. I wish you grow well. 

- Jerry Davos

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/88e7251a-809e-4c1e-aaeb-5d07304376cd)

The mask color value specifies an exact specific value, not a range of colors.

**Comment by jerrydavos** [comment]
I remapped the range... Still no luck 
![AnimateDiff_00008](https://github.com/user-attachments/assets/6cb53c7f-6322-4667-a114-dae5ff25eac2)

![image](https://github.com/user-attachments/assets/7ba76cc8-8e2d-44e2-b548-1d4932ab9fc0)
[Animatediff Regional Prompts_Remaped.json](https://github.com/user-attachments/files/16350272/Animatediff.Regional.Prompts_Remaped.json)

**Comment by ltdrdata** [comment]
You can see empty region between each mask.

![image](https://github.com/user-attachments/assets/b115d735-f9b8-4e15-9e18-33dd71502323)

You need to dilate one of the mask.

![image](https://github.com/user-attachments/assets/ec28f262-100b-4562-9fb4-e6304afb0efb)

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/085fcc29-02f3-4f6a-851e-2e19b16a0619)

`dilation` is added to RegionalConditioningColorMask

**Comment by jerrydavos** [comment]
Hey, when I use a **directory** as input for masks it broke. 

![image](https://github.com/user-attachments/assets/e694b465-6b45-4a05-83ee-5737ca856ba8)
![image](https://github.com/user-attachments/assets/c872d291-e118-4269-9804-b6eaf38aa747)


```
Traceback (most recent call last):
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\regional_nodes.py", line 186, in doit
    mask = utils.dilate_mask(mask, dilation)
  File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\libs\utils.py", line 312, in dilate_mask
    mask_dilated = cv2.dilate(mask.numpy(), kernel, iterations=1)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix.cpp:1099: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'cv::Mat::locateROI'


#790 [RegionalConditioningColorMask //Inspire]: 0.27s
Prompt executed in 0.29 seconds
```

For Only **1** frame: it didn't gave any error: 
![image](https://github.com/user-attachments/assets/a574b0fd-3198-46d0-9bd0-826bae4da918)

**Comment by ltdrdata** [comment]
> Hey, when I use a **directory** as input for masks it broke.
> 
> ![image](https://private-user-images.githubusercontent.com/152957217/351603246-e694b465-6b45-4a05-83ee-5737ca856ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjEzNzEsIm5iZiI6MTcyMTgyMTA3MSwicGF0aCI6Ii8xNTI5NTcyMTcvMzUxNjAzMjQ2LWU2OTRiNDY1LTZiNDUtNGEwNS04M2VlLTU3MzdjYTg1NmJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxMTM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTU4NTVkNTFiNmQ1Mjk0MTc5NWU3ZDUyMDRlZjY2YzY1MDljN2ZkN2Q5Yzc2ZTkzNThmM2I4M2UyOGUwOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TGHfI_rpsHzmevOuZJFpw22wJ7KZ2g2yqlM4vOIe178) ![image](https://private-user-images.githubusercontent.com/152957217/351605606-dc89856d-c0cc-407b-990f-26e4c41137f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjEzNzEsIm5iZiI6MTcyMTgyMTA3MSwicGF0aCI6Ii8xNTI5NTcyMTcvMzUxNjA1NjA2LWRjODk4NTZkLWMwY2MtNDA3Yi05OTBmLTI2ZTRjNDExMzdmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxMTM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzQ3M2E4ZjgzZmNhMTVmMWZjMGUxNmM2NTA3MWEyMDczYmE5YTVlNWVhYWQ3NmM1MmE1ZDk5Y2UzNGFiYzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f-R-GK0bxpxYiXDfryT-_YuQ0CRcoIAIZ9dIWES_iWs)
> 
> ```
> !!! Exception during processing!!! OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix.cpp:1099: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'cv::Mat::locateROI'
> 
> Traceback (most recent call last):
>   File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\regional_nodes.py", line 186, in doit
>     mask = utils.dilate_mask(mask, dilation)
>   File "F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\libs\utils.py", line 312, in dilate_mask
>     mask_dilated = cv2.dilate(mask.numpy(), kernel, iterations=1)
> cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix.cpp:1099: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'cv::Mat::locateROI'
> 
> 
> #789 [RegionalConditioningColorMask //Inspire]: 0.22s
> Prompt executed in 2.35 seconds
> ```
> 
> For Only **1** frame: it didn't gave any error: ![image](https://private-user-images.githubusercontent.com/152957217/351605393-280fcaf9-0d60-4e2a-9a66-a0e322313a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjEzNzEsIm5iZiI6MTcyMTgyMTA3MSwicGF0aCI6Ii8xNTI5NTcyMTcvMzUxNjA1MzkzLTI4MGZjYWY5LTBkNjAtNGUyYS05YTY2LWEwZTMyMjMxM2E4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxMTM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTViM2EyMDVlNjhmMzgzMGQ5MGZhNDZmN2E5MjIwNWZiYmNlODI3YTA5ODFhYWEzYjY1OTkzNmZjOTFlNjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QS0emSBkfT_-U02hfJhOuNG7lY86LyXmMCxn2_22ReM)

This is fixed.
