### ISSUE TITLE
[Feature Request] Ability to save LoRa blockweights

### ISSUE THREAD

**Issue by Smorgin** [ltdrdata/ComfyUI-Inspire-Pack#131]
It would be nice to be able to save the blockweights once you find a setting you like. For generation speed it's faster to take the lora with changed blocks, save it as it's own lora, and then use it normally (also cleaner node setups with stuff like powerloaders). But currently you need to find the blocks you want then load/save it in a separate thing like supermerger. Would love to be able to save it natively!

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/save-load-lbw.png

A `LoraSave` node has been added to the ComfyUI core itself. It is possible to save using this. However, this method doesn't save the model as-is, but processes it slightly to fit the LoRA framework according to the set rank, so the results differ slightly from LBW application.

I've separately added a `SaveLBW` node to the Inspire Pack that can save with completely identical settings, so please refer to that.

However, `LoraSave` has the advantage of being able to load through the `LoRA Loader` and the ability to save the results of applying multiple LoRAs in layers.
