### ISSUE TITLE
Feature request "Color Preprocessor Provider (SEGS)"

### ISSUE THREAD

**Issue by nkampel** [ltdrdata/ComfyUI-Inspire-Pack#14]
Hello,

First, thank you for your incredible work!

I'm encountering an issue with the facedetailer adding color to my monochrome images. Is there a possibility of adding a "Color Preprocessor Provider (SEGS)" feature?

Your consideration of this request would be greatly appreciated.

Thank you,

**Comment by ltdrdata** [comment]
Added on 353493eadc86e4f6f0b796fb0d2ea3bfa25cf771
