### ISSUE TITLE
Error occurred when executing RetrieveBackendDataNumberKey //Inspire:  'NoneType' object is not iterable

### ISSUE THREAD

**Issue by yytokreal** [ltdrdata/ComfyUI-Inspire-Pack#141]
当我第一使用RetrieveBackendDataNumberKey的时候，出现这个提示
![download](https://github.com/user-attachments/assets/928296eb-d5ad-45a2-ac71-774b4f7386f7)
![download](https://github.com/user-attachments/assets/8fba8482-7d17-4b33-9cb1-6be21759099c)
要如何处理呢？

**Comment by ltdrdata** [comment]
To use Retrieve Backend Data, you first need to put data into the cache using Cache Backend Data.
