### ISSUE TITLE
AttributeError: type object 'RegionalSampler' has no attribute 'separated_sample'

### ISSUE THREAD

**Issue by changaolee** [ltdrdata/ComfyUI-Inspire-Pack#147]
I use the latest version, and got AttributeError: type object 'RegionalSampler' has no attribute 'separated_sample'
how to fix this

**Comment by 19KRO** [comment]
> I use the latest version, and got AttributeError: type object 'RegionalSampler' has no attribute 'separated_sample' how to fix this

Since you closed the thread can you tell how did you fixed that error?
I've encountered the same situation after comfy update -_-

**Comment by ltdrdata** [comment]
> > I use the latest version, and got AttributeError: type object 'RegionalSampler' has no attribute 'separated_sample' how to fix this
> 
> Since you closed the thread can you tell how did you fixed that error? I've encountered the same situation after comfy update -_-

Just update Impact Pack to latest version.
