### ISSUE TITLE
Constant errors if using own prompts rather than the example text files

### ISSUE THREAD

**Issue by vamanetta** [ltdrdata/ComfyUI-Inspire-Pack#148]
Hello ltdrdata,

Your example files only have 3 prompts and I want to run 200 prompts. I tried to follow the format that you made but it's not clear why my own prompts are not working. When I loaded up your example it generated no problem but when I tried my own it just kept throwing errors about the unzip:

Error occurred when executing UnzipPrompt //Inspire:

UnzipPrompt.doit() missing 1 required positional argument: 'zipped_prompt'

File "C:\work\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 313, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "C:\work\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 188, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "C:\work\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
res_value = old_func(*final_args, **kwargs)
File "C:\work\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 161, in map_node_over_list
process_inputs({})
File "C:\work\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in process_inputs
results.append(getattr(obj, func)(**inputs))

An example of my prompt format is but imagine that it's 200 long: 

positive:Futuristic survey ship, sleek design, solar panels, exploring Greenland fjord, summer season, melting icebergs, clear blue water, rocky green shores, wildflowers, distant snow-capped mountains, drone swarm mapping coastline, holographic displays on deck, scientists with high-tech equipment, midnight sun low on horizon, reflections on calm water, mist rising from fjord, 8K resolution, hyper-realistic, cinematic lighting, aerial perspective

negative:text
-----------------
positive:Futuristic Greenlandic city, vast plain atop towering cliffs, overlooking majestic fjord, gleaming skyscrapers with Nordic-inspired architecture, transparent dome covers sections of city, advanced wind turbines, vertical farms integrated into buildings, elevated mag-lev train system, hovering personal transport vehicles, holographic billboards, melting glaciers in distance, midnight sun low on horizon, vibrant aurora borealis in sky, blend of modern and traditional Inuit design elements, lush rooftop gardens, waterfall cascading from cliff to fjord, 8K resolution, hyper-realistic, dramatic lighting, wide-angle panoramic view

negative:text
-----------------
positive:Futuristic Greenlandic city, vast plain atop towering cliffs, overlooking majestic fjord, gleaming skyscrapers with Nordic-inspired architecture, transparent dome covers sections of city, advanced wind turbines, vertical farms integrated into buildings, elevated mag-lev train system, hovering personal transport vehicles, holographic billboards, melting glaciers in distance, midnight sun low on horizon, vibrant aurora borealis in sky, blend of modern and traditional Inuit design elements, lush rooftop gardens, waterfall cascading from cliff to fjord, 8K resolution, hyper-realistic, dramatic lighting, wide-angle panoramic view

negative:text

I have found no guide on how to use more than 3 prompts just the example 2 file you made. What is the format so it will not throw errors. I want to automate my work so I can walk away and come back to pick the best and move on? 

Thanks.

**Comment by ltdrdata** [comment]
Make sure up to date Inspire Pack.

**Comment by vamanetta** [comment]
Hey it seems it's fixed with update thanks.
