### ISSUE TITLE
 (IMPORT FAILED) ComfyUI Inspire Pack

### ISSUE THREAD

**Issue by ovtoprak** [ltdrdata/ComfyUI-Inspire-Pack#149]
I am a bit new to these but I tried to install this on 2 different Comfy UI installation (1 from Stability Matrix, 2nd from Portable Windows Installation). Trying to install this through ComfyUI-Manager. Getting the same error.

Where does it go wrong, please?

**Comment by ltdrdata** [comment]
What message is displayed on terminal?

**Comment by ovtoprak** [comment]
> What message is displayed on terminal?

It was on Custom Nodes Manager but not anymore, it is weird. I think I only installed this one since I see the error, not sure this is related to the solution.

git clone https://github.com/city96/ComfyUI-GGUF ComfyUI/custom_nodes/ComfyUI-GGUF
.\python_embeded\python.exe -s -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-GGUF\requirements.txt

Thank you for getting back to me anyway!
