### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GraemRus** [ltdrdata/ComfyUI-Inspire-Pack#157]
![image](https://github.com/user-attachments/assets/54af8ddb-20e8-42d3-a15b-e6bc84f48b45)
![image](https://github.com/user-attachments/assets/8c94437c-73bd-43fd-ba61-74d121c23beb)
![image](https://github.com/user-attachments/assets/74b5257b-75f6-4aa4-b59e-5e0dbf26fa96)

I get this after booting. rebooting and reinstalling doesn't help.
 
![image](https://github.com/user-attachments/assets/b1941674-ff40-481b-97db-0a31a67043ff)
[comfyui.log](https://github.com/user-attachments/files/16945932/comfyui.log)

**Comment by ltdrdata** [comment]
Execute this in cmd
`S:\!COMFY\ComfyUI_windows_portable\python_embeded\python.exe -m pip install opencv-python`
