### ISSUE TITLE
DWPreprocessor

### ISSUE THREAD

**Issue by JARRGH** [ltdrdata/ComfyUI-Inspire-Pack#159]
hi, 
![image](https://github.com/user-attachments/assets/d3d70206-e2a8-4ab1-b95c-e1b28a75f24c)

even with inspure pack and control net aux installed 
![image](https://github.com/user-attachments/assets/3c2836fc-5021-4c03-8d8e-865ee8aa861c)

 anime_ lineart and Hed ,   had the same issue , "anime lineart preprocessor "

i have uninstall and install everything and still , same issue

**Comment by ltdrdata** [comment]
You need to move your ComfyUI installation to the root.
In Windows, if a specific setting is not configured in the registry, the maximum path length is limited to 260 characters.
