### ISSUE TITLE
Feature request Text from Directory

### ISSUE THREAD

**Issue by hightechpresha** [ltdrdata/ComfyUI-Inspire-Pack#16]
Can you create a text import function along the lines of Image from Directory that allows us to load multiple content from text files in a folder?

**Comment by ltdrdata** [comment]
There are already multiple nodes for reading text at the moment. In the Inspire Pack, we have "Load Prompts From Dir" and "Load Prompts From File" for fetching prompts, and in WAS-NS, it provides the capability to read text files and select specific lines.

**Comment by hightechpresha** [comment]
That is correct but we want to read a text file and when it is completely read switch to the next text file to process it. For a single text file this works fine but we have not found a node to read multiple text files from a folder. But you are right that should work with the "Load Prompts From Dir".

**Comment by ltdrdata** [comment]
> That is correct but we want to read a text file and when it is completely read switch to the next text file to process it. For a single text file this works fine but we have not found a node to read multiple text files from a folder. But you are right that should work with the "Load Prompts From Dir".

If your are trying iterating whole prompts in dir, you can use "Load Prompts From Dir".

It supports multiple prompts in a single file, too.

Just it requires some specific format instead of text lines.
