### ISSUE TITLE
Why are there 58 blocks for Flux in the Lora Loader when there should be only 57?

### ISSUE THREAD

**Issue by codecomputation** [ltdrdata/ComfyUI-Inspire-Pack#162]
Flux has 19 double blocks and 38 single blocks . Where does the extra block come from?

**Comment by ltdrdata** [comment]
The extra block is a base block, which usually includes remaining blocks such as the text encoder.
It's important to note that even though the base block may consist of multiple blocks, individual adjustment is not possible. It can only be controlled collectively through the weight of the first weight.

**Comment by codecomputation** [comment]
Thanks for the quick reply.
