### ISSUE TITLE
how to connect a lora_name input?

### ISSUE THREAD

**Issue by vigee88** [ltdrdata/ComfyUI-Inspire-Pack#164]
when i use Lora Block Weight node,convert lora_name to input,But I couldn't find a matching node to connect 。
I hope to get assistance。
thanks！
![QQ图片20240924173406](https://github.com/user-attachments/assets/112de8c5-cb9a-4ce8-bbbd-c6f4950cddf1)

**Comment by ltdrdata** [comment]
You can connect `Primitive Node`.
Double clicking the slot adds `Primtive Node` automatically.
