### ISSUE TITLE
[Bug] Strange steps difference in KSampler (inspire) using ddim_uniform scheduler

### ISSUE THREAD

**Issue by LukeG89** [ltdrdata/ComfyUI-Inspire-Pack#166]
Why is there a difference in steps in KSampler (inspire) using `ddim_uniform` scheduler?

For example:

- Set 30 steps -> 31 are made
- Set 60 steps -> 63 are made
- Set 80 steps -> 84 are made

https://github.com/user-attachments/assets/44ab846b-bdea-4685-a61a-8aa30494e337

**Comment by LukeG89** [comment]
@ltdrdata Does this only happen to me?
I've also tried disabling all custom nodes except the Manager and the Impact and Inspire Packs.

**Comment by ltdrdata** [comment]
This is a phenomenon occurring in `ddim_uniform`, and it's an issue with the core itself. Please inquire at the ComfyUI repo.

**Comment by LukeG89** [comment]
@ltdrdata But it only happens with your KSampler Inspire, I don't have this issue using the ComfyUI. How is it possible?

**Comment by ltdrdata** [comment]
> @ltdrdata But it only happens with your KSampler Inspire, I don't have this issue using the ComfyUI ones. How is it possible?

In my tests, the same issue is occurring in the KSampler of the core.
