### ISSUE TITLE
[Feature Request] Suggested Flux Lora Block Weight preset: Negate

### ISSUE THREAD

**Issue by envy-ai** [ltdrdata/ComfyUI-Inspire-Pack#167]
I noticed that if you try to set a lora's weight to -1 in flux, you often end up with a dim image and mostly static.  I've spent some time experimenting with layers and determined that if you zero some of them out, it works well.  This is what I've come up with:

-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

**Comment by ltdrdata** [comment]
When you turn on the inverse switch, it not only changes the block weight to negative, but also allows both positive and negative weights. Make use of this feature.
In the default settings, the functionality of negative weights is intentionally blocked.
