### ISSUE TITLE
MiDaS Error

### ISSUE THREAD

**Issue by frznfrg** [ltdrdata/ComfyUI-Inspire-Pack#168]
Dear, please help me on this error. I tried to run it on ComfyUI but I got this error in MiDas. 

[MiDaS error.txt](https://github.com/user-attachments/files/17177777/MiDaS.error.txt)
[IPAdapter_Advanced.json](https://github.com/user-attachments/files/17177778/IPAdapter_Advanced.json)

**Comment by ltdrdata** [comment]
Your ComfyUI installation path is too deep. Windows doesn't handle long paths well. Move ComfyUI under C:\ and reinstall the controlnet aux custom nodes.
