### ISSUE TITLE
Load Images From Directory

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Inspire-Pack#17]
Thought I would try and use this node to read embeds for IPadapter.  Not sure where to put these, so I wanted to try this. However, I can't seem to get the path to work correctly in windows.  I get this error:

Error occurred when executing LoadImagesFromDir //Inspire:

object of type 'NoneType' has no len()

File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 96, in get_output_data
output_is_list = [False] * len(results[0])

**Comment by ltdrdata** [comment]
If you have a directory like `ComfyUI\Inputs\style1`, you can specify the path in the form of `.\Inputs\style1`.

**Comment by sedetweiler** [comment]
Thanks!
