### ISSUE TITLE
After converting random seed to input, save workflow and then open workflow. There is a problem with random seed input.

### ISSUE THREAD

**Issue by wencxxxxxx** [ltdrdata/ComfyUI-Inspire-Pack#172]
After converting random seed to input, save workflow and then open workflow. There is a problem with random seed input.
![屏幕截图 2024-10-11 133301](https://github.com/user-attachments/assets/64eeffe6-f963-41f2-b0e9-c0b4774b1880)

**Comment by ltdrdata** [comment]
I cannot understand what issue you are talking about.

**Comment by wencxxxxxx** [comment]
Problem solved. Thank you
