### ISSUE TITLE
Request: Please change the Load Prompt from File node so that we can freely choose any file location.

### ISSUE THREAD

**Issue by n0valis** [ltdrdata/ComfyUI-Inspire-Pack#177]
...and not being forced to use some dir somewhere predefined.

Thank you.

**Comment by ltdrdata** [comment]
This is implemented.
Now you can specify `inspire_prompts` from `extra_model_paths.yaml`.

**Comment by n0valis** [comment]
Can you please give an example on how to do that? How the structure looks.

**Comment by ltdrdata** [comment]
> Can you please give an example on how to do that? How the structure looks.

```
other_ui2:
   base_path: /mnt/teratera/test_path2
   inspire_prompts: inspire_prompts
```

**Comment by n0valis** [comment]
How about Load prompt from dir? It seems that it's still bound to ComfyUI-Inspire-Pack\prompts. Why?
