### ISSUE TITLE
Lora weight when using Inspire Wildcard Processor not working?

### ISSUE THREAD

**Issue by gachapengames** [ltdrdata/ComfyUI-Inspire-Pack#178]
Thank you so much for making so many great nodes for Comfyui! I have been experimenting with the Inspire Wildcard Processor, and at least for me it seems to have an issue applying lora strength? Here is an example:

When entering <lora:directory/exampleLORA>

and changing it to 

<lora:directory/exampleLORA:.2> for .2 strength it seems to have no effect, still looks 1 strength.

Increasing it to <lora:directory/exampleLORA:3> or 3 strength for example destroys the generation, so it seems that lora strength IS implemented?

Trying <lora:directory/exampleLORA:.00001> still looks like at least .5-.7, and even a weight of 0 still greatly applies the lora.

**Comment by ltdrdata** [comment]
Oh...You cannot omit the leading zero in decimal numbers. You must specify it like 0.1.

**Comment by ltdrdata** [comment]
You need to update Impact Pack.
