### ISSUE TITLE
[BUG] Ksampler (Inspire) Input Pin turn into non-functioning "scheduler_func_opt" pin

### ISSUE THREAD

**Issue by Shyryp** [ltdrdata/ComfyUI-Inspire-Pack#179]
After updating ComfyUI and Inspire Pack in the last week I got a problem (bug) with Ksampler (Inspire):
All widget nodes that are switched to Input mode, after rebooting ComfyUI and opening a workflow, turn into a non-functioning pin named "scheduler_func_opt".

For example, the input pin "Denosing" turned into "scheduler_func_opt":
![image](https://github.com/user-attachments/assets/f6c74f04-c55e-4b9f-98ac-314bb72a2b03)

In the console I get the following error:
```
Failed to validate prompt for output 183:
* KSampler //Inspire 3:
- Return type mismatch between linked nodes: scheduler_func_opt, FLOAT != SCHEDULER_FUNC
```

The problem is "fixed" if you convert the pin from Input format to Widget format and back. That is, after this, the Input pin works fine. But if you reboot ComfyUI, it turns into scheduler_func_opt again.

Please fix the problem or give advice on how to avoid this problem with this node.

Thanks!

**Comment by ltdrdata** [comment]
You need to recreate that node.
Node of old workflow is no longer backward compatible in new UI.
