### ISSUE TITLE
GlobalSeed: seed value taken by the Save Image node for the filename is incorrect

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Inspire-Pack#18]
When randomization is turned on, together with control_before_generate, then when using GlobalSeed's value in Save Image node, the value prior to randomization is used for the filename.

Instead it should be the randomized value.

Here is an example workflow that demonstrates the issue:

![1_00001_](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/55cd3dfc-35ea-4f6e-b160-e88dbb772383)

Here, the seed value prior to randomization was "1", and it is used for the filename "1_00001_.png". However the randomized seed is 1054289837613396.

**Comment by ltdrdata** [comment]
I do added '$GlobalSeed.value$' on 65c27e6469acc47c280c1696b7184e6c9ccd435c.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/GlobalSeed.md
