### ISSUE TITLE
[feature] cache backend store the model in CPU memory?

### ISSUE THREAD

**Issue by t00350320** [ltdrdata/ComfyUI-Inspire-Pack#183]
as this git code shows,
```
cache = TaggedCache(cache_settings) 
```
the model data will stored in CPU memory? Will or doest it properly to store these datas in GPU in advance？

**Comment by ltdrdata** [comment]
The cache here is for node output caching. It doesn't affect VRAM. 
VRAM should be managed by ComfyUI's own management system.

**Comment by t00350320** [comment]
> The cache here is for node output caching. It doesn't affect VRAM.
> VRAM should be managed by ComfyUI's own management system.

thanks for your reply, my question is , where is the cache backend data, if i put shared checkpoint ->lora->cache backend data in one workflow, then retrieve the data in another workflow,when and how the cache data moved to , from where to gpu? after the inference  process, will retrieved data removed from gpu or hosted by retrieve node in memory? please help or where can i find a gentle way to preload ckpy,lora,controlnet by inspire pack? very appreciate

**Comment by ltdrdata** [comment]
This is a question about basic ComfyUI behavior.

By default, models loaded with Checkpoint Loader are loaded into system RAM. Then, when actually using the model with nodes like KSampler, it moves to VRAM.

When --disable-smart-memory is deactivated, if a new model needs to enter VRAM and there isn't enough VRAM, it moves existing models from VRAM back to system RAM and loads the new model into VRAM.

If you use the default Checkpoint Loader to load a model and then remove that node and run the workflow, or select a different model and run it, it completely wipes the previously loaded model from memory, whether it's in VRAM or system RAM.

The role of cache in Inspire Pack is to prevent models from being completely removed even when the node that loaded the model in the workflow is deleted or changed.
