### ISSUE TITLE
[request] how many cache backend data nodes can we support?

### ISSUE THREAD

**Issue by t00350320** [ltdrdata/ComfyUI-Inspire-Pack#186]
an init  workflow has many nodes(28 nodes) to be cached, but always currupted before cached over.
after remove some nodes, the workflow can be loaded completely.
So, i wonder do we have a proper nodes number limit。
```
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_in.alpha
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_in.lora_down.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_in.lora_up.weight
lora key not loaded: lora_unet_down_blocks_0_attentions_0_proj_out.alpha
```
thanks a lot

**Comment by ltdrdata** [comment]
For the LoRA key issue, please inquire with the ComfyUI core repository along with the LoRA file being used.

**Comment by t00350320** [comment]
> For the LoRA key issue, please inquire with the ComfyUI core repository along with the LoRA file being used.

Sorry I didn't explain clearly. If i remove some nodes(not include this lora model), the workflow can be loaded correctly,the lora also can be loaded correctly.
I mean, abnormal results are not the same every time if i load the full workflow
[init_workflow.json](https://github.com/user-attachments/files/17743912/init_workflow.json)

So i asked you do we have some limition for cache nodes usage, or it may have some relation with ComfyUI itself, but i have no idea how to dig it out

**Comment by ltdrdata** [comment]
> Sorry I didn't explain clearly. If i remove some nodes(not include this lora model), the workflow can be loaded correctly,the lora also can be loaded correctly. I mean, abnormal results are not the same every time if i load the full workflow [init_workflow.json](https://github.com/user-attachments/files/17743912/init_workflow.json)
> 
> So i asked you do we have some limition for cache nodes usage, or it may have some relation with ComfyUI itself, but i have no idea how to dig it out

When not using backend cache, the cache is dependent on the workflow.
The purpose of using backend cache is to maintain information independently from the workflow's cache.

In other words, it means that even when loading a new workflow, the previously executed cache is maintained as is.

**Comment by t00350320** [comment]
> > Sorry I didn't explain clearly. If i remove some nodes(not include this lora model), the workflow can be loaded correctly,the lora also can be loaded correctly. I mean, abnormal results are not the same every time if i load the full workflow [init_workflow.json](https://github.com/user-attachments/files/17743912/init_workflow.json)
> > So i asked you do we have some limition for cache nodes usage, or it may have some relation with ComfyUI itself, but i have no idea how to dig it out
> 
> When not using backend cache, the cache is dependent on the workflow. The purpose of using backend cache is to maintain information independently from the workflow's cache.
> 
> In other words, it means that even when loading a new workflow, the previously executed cache is maintained as is.

yes, definitely right, So step1, l loaded all ckpt,loras,controlnet,upscale, etc in init_workflow.json as i posted before. Then  step2, real service workflows like service1.json , service2.json ,etc loaded . The current issue is, the workflow can't be loaded exactly in step1, -_-

**Comment by ltdrdata** [comment]
Have you investigated the cached items through this node?
![image](https://github.com/user-attachments/assets/f9205be5-dec0-4f0a-ace8-78c51201cc93)

**Comment by t00350320** [comment]
> Have you investigated the cached items through this node? ![image](https://private-user-images.githubusercontent.com/128333288/386477163-f9205be5-dec0-4f0a-ace8-78c51201cc93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTEwNjgsIm5iZiI6MTczMTY1MDc2OCwicGF0aCI6Ii8xMjgzMzMyODgvMzg2NDc3MTYzLWY5MjA1YmU1LWRlYzAtNGYwYS1hY2U4LTc4YzUxMjAxY2M5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNjA2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzQ4ZDIxNTRkYzJlNDRiNGZlMDFkMGRkZDVkNmQwZGUyNWRjZmQyYTFlMGE1YTk5MjIyYzg4ZWZjNzkxZDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S6VJhuP-xR-eGPogkRTL9pKih03O6RJln73hrQFTxyU)

i think it miss some nodes
```
---- [String Key Caches] ----
cn15 tile: N/A(tag)
sdxl cn canny: N/A(tag)
sdxl base1.0 clip: N/A(tag)
sdxl base1.0 vae: N/A(tag)
sdxl cn tile: N/A(tag)
sdxl latteart vae: N/A(tag)
sdxl lineart: N/A(tag)
upscale2x: N/A(tag)
cn15 lineart: N/A(tag)
cn1.5 depth: N/A(tag)
sd1.5 clip: N/A(tag)
sd1.5 vae: N/A(tag)
sd15 vae-ft-mse-840000: N/A(tag)
midas loader: N/A(tag)
sdxl latteart: N/A(tag)
sdxl latteart clip: N/A(tag)
sd1.5 lora gold: N/A(tag)
sd1.5 lora sand: N/A(tag)
sd1.5 ertonghuiben: N/A(tag)
sd1.5 ertonghuiben clip: N/A(tag)
stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors: ckpt
autismmixSDXL_autismmixConfetti.safetensors: ckpt
realisticVisionV51_v51VAE.safetensors: ckpt
allInOnePixelModel_v1_sd15.ckpt: ckpt
sd1_5/AWPainting_v1.4.safetensors: ckpt
sdxl sumiaolora: lora
pixel sd15: lora
pixel sd15 clip: lora

---- [Number Key Caches] ----

---- [TagCache Settings] ----
ckpt: 5
latent: 100
image: 100
: 20
lora: 20
```

**Comment by t00350320** [comment]
TagCache Settings will limit the nodes number? or should i set some tag for every node? have no idea

**Comment by ltdrdata** [comment]
> birefnet

Oh, that's right. If you don't assign a tag, it will be treated as "N/A," which will count towards the 20 tag limit.
You can resolve this by either increasing the configuration for empty tags in "Show Cached Info" or assigning a separate tag to the cache in birefnet.

**Comment by t00350320** [comment]
> > birefnet
> 
> Oh, that's right. If you don't assign a tag, it will be treated as "N/A," which will count towards the 20 tag limit. You can resolve this by either increasing the configuration for empty tags in "Show Cached Info" or assigning a separate tag to the cache in birefnet.

it finally works. ~-~
Thank you very much.
