### ISSUE TITLE
Incompatible with Nested Nodes

### ISSUE THREAD

**Issue by MrGingerSir222** [ltdrdata/ComfyUI-Inspire-Pack#19]
Just letting you (and others) know that this node conflicts with the Nested Nodes. I don't know enough about coding to know if this issue is fixable or not.

**Comment by ltdrdata** [comment]
I need more specific information.

**Comment by MrGingerSir222** [comment]
If I have both the Nested Nodes and Inspire Pack installed, then the nested nodes will not run in a workflow. It gives this error: "TypeError: undefined is not an object (evaluating 'app.graph._nodes_by_id[node_id].widgets')" 
However, if I remove inspire Pack, then the nested nodes run just fine.

**Comment by ltdrdata** [comment]
It seems Nested Nodes is broken due to recent ComfyUI update.
I'll check it after it is updated.

**Comment by ltdrdata** [comment]
Hotfix is applied. And `Global Seed` will work. But nest node's seed value won't updated visually.

https://github.com/ssitu/ComfyUI_NestedNodeBuilder/issues/16#issuecomment-1750900355
