### ISSUE TITLE
[Bug] "LoRA Loader (Block Weight)" for Flux, there is a mismatch when the LoRA does not have some blocks

### ISSUE THREAD

**Issue by diodiogod** [ltdrdata/ComfyUI-Inspire-Pack#191]
So, I had trained my Flux Lora with only the single blocks 0-18. So it does not have double or the remain single ones. 
For reference, this is an image with all zeros on the blocks:
![Captura de tela 2024-11-30 170327](https://github.com/user-attachments/assets/6782414d-d7fe-43a6-88af-0af757d42b57)

If I input to the LoRA Loader (Block Weight) a full 58 values with just the single 0-19 as 1s and the rest as 0s, like this:

1,
0,0,0,0,
0,0,0,0,
0,0,0,
0,0,0,0,
0,0,0,0
,

1,1,1,1,
1,1,1,1,
1,1,1,
1,1,1,1,
1,1,1,1
,
0,0,0,0,
0,0,0,0,
0,0,0,
0,0,0,0,
0,0,0,0

it gives me an image as if the LoRa was not applied:

![Captura de tela 2024-11-30 170417](https://github.com/user-attachments/assets/0ada5309-58d4-4c04-a7a2-dee9cad869a3)

If I input the values like this:
1,
1,1,1,1,
1,1,1,1,
1,1,1,
1,1,1,1,
1,1,1,1
,

0,0,0,0,
0,0,0,0,
0,0,0,
0,0,0,0,
0,0,0,0
,
0,0,0,0,
0,0,0,0,
0,0,0,
0,0,0,0,
0,0,0,0

It changes the image:

![Captura de tela 2024-11-30 170256](https://github.com/user-attachments/assets/f38cb7c5-4e55-4b97-91dc-21e742982eda)

For sanity check, this is the result when I select the preset "double all" on the node. The lora doesn't have any doubles, still, the image changes:

![Captura de tela 2024-11-30 170631](https://github.com/user-attachments/assets/1612a92e-02ad-4b59-8480-05ba67446d8b)

I think it reads the first values and applied them to the first blocks it finds. But wouldn't it be more correct to match each block to each value?

This is my workflow: https://drive.google.com/file/d/1ou5cNKm1xL8bAnzYNJsZXSqFdUDib1aR/view?usp=sharing
This is my LoRa: https://drive.google.com/file/d/1wxfjsoyi52Q1XbY5U2_ZlCgfVXK41Zvt/view?usp=sharing

**Comment by ltdrdata** [comment]
The enumeration of weights is generally based on the principle of sequential matching to allow for some flexibility in application. To address this, Inspire Pack also provide a syntax that allows settings based on block names.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/LoraBlockWeight.md#named-weight-syntax

**Comment by diodiogod** [comment]
> The enumeration of weights is generally based on the principle of sequential matching to allow for some flexibility in application. To address this, Inspire Pack also provide a syntax that allows settings based on block names.
> 
> https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/LoraBlockWeight.md#named-weight-syntax

But following this logic, the presets are wrong then, because if I choose doubles and my LoRa does not contain any double blocks it get's applied to other blocks... Looks confusing to me.

**Comment by ltdrdata** [comment]
> > The enumeration of weights is generally based on the principle of sequential matching to allow for some flexibility in application. To address this, Inspire Pack also provide a syntax that allows settings based on block names.
> > https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/LoraBlockWeight.md#named-weight-syntax
> 
> But following this logic, the presets are wrong then, because if I choose doubles and my LoRa does not contain any double blocks it get's applied to other blocks... Looks confusing to me.

In fact, the name in the preset doesn't hold any real meaning; it's more like a description. 
I'm still considering how to best handle the differences in structure between each LoRA.

**Comment by diodiogod** [comment]
> > > The enumeration of weights is generally based on the principle of sequential matching to allow for some flexibility in application. To address this, Inspire Pack also provide a syntax that allows settings based on block names.
> > > https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/LoraBlockWeight.md#named-weight-syntax
> > 
> > 
> > But following this logic, the presets are wrong then, because if I choose doubles and my LoRa does not contain any double blocks it get's applied to other blocks... Looks confusing to me.
> 
> In fact, the name in the preset doesn't hold any real meaning; it's more like a description. I'm still considering how to best handle the differences in structure between each LoRA.

Thanks for the explanations! Now, this is just my opinion. I think i'ts better to always match each position to each block and require a 58 value always, or else error out. Or accept some other kind of format like @nihedon did with a 19 format on his forge extention https://github.com/nihedon/sd-webui-lora-block-weight/issues/2#issuecomment-2390632995

**Comment by diodiogod** [comment]
Even though IMO the sequential number should work differently, it's not my call. 
The named format works perfectly!! Thanks for that.
So I'm closing this!
