### ISSUE TITLE
Concat Conditionings with Multiplier Stopped working in new versions comfyui

### ISSUE THREAD

**Issue by BenderBlender** [ltdrdata/ComfyUI-Inspire-Pack#194]
Concat Conditionings with Multiplier Stopped working in new versions comfyui
![image](https://github.com/user-attachments/assets/f6f17b10-e214-4de9-a41c-411bbf1eff8c)

**Comment by ltdrdata** [comment]
Please post the comfyui.log file.

**Comment by ltdrdata** [comment]
literally you need to install `comfy_PoP`.

**Comment by BenderBlender** [comment]
Okay, thanks!
