### ISSUE TITLE
how to fix this ? thx!

### ISSUE THREAD

**Issue by Elminsst** [ltdrdata/ComfyUI-Inspire-Pack#195]
### Loading: ComfyUI-Inspire-Pack (V1.9)
Warning: INPUT_TYPES and function arguments don't match in SaveImageCustomNode, input_types: ['self', 'images', 'filename_prefix', 'subfolder_dir'], function arguments: ['self', 'images', 'filename_prefix', 'subfolder_dir', 'prompt', 'extra_pnginfo', 'self']
Warning: INPUT_TYPES and function arguments don't match in SaveImageWebpCustomNode, input_types: ['self', 'images', 'filename_prefix', 'subfolder_dir', 'quality', 'lossless', 'compression', 'optimize', 'metadata_string'], function arguments: ['self', 'images', 'filename_prefix', 'subfolder_dir', 'prompt', 'extra_pnginfo', 'quality', 'lossless', 'compression', 'optimize', 'metadata_string', 'self']
Warning: args in function arguments in ResizeImageNode, skipping argument validation
Warning: args in function arguments in ResizeImageResolution, skipping argument validation
Warning: args in function arguments in Base64DecodeNode, skipping argument validation
Warning: args in function arguments in InvertImageNode, skipping argument validation
Warning: args in function arguments in ResizeScaleImageNode, skipping argument validation
Warning: args in function arguments in ResizeShortestToNode, skipping argument validation
Warning: args in function arguments in ResizeLongestToNode, skipping argument validation
Warning: args in function arguments in ConvertGreyscaleNode, skipping argument validation
Warning: args in function arguments in RotateImageNode, skipping argument validation
Warning: args in function arguments in BrightnessNode, skipping argument validation
Warning: args in function arguments in ContrastNode, skipping argument validation
Warning: args in function arguments in SharpnessNode, skipping argument validation
Warning: args in function arguments in ColorNode, skipping argument validation
Warning: args in function arguments in ConvertRGBNode, skipping argument validation
Warning: args in function arguments in ThresholdNode, skipping argument validation
Warning: args in function arguments in SDWebuiAPINode, skipping argument validation
Warning: args in function arguments in SDWebuiAPIFallbackNode, skipping argument validation

**Comment by ltdrdata** [comment]
That's not a issue of Inspire Pack.

Disable the `ComfyUI-LogicUtils` custom node.
