### ISSUE TITLE
the use of 'name' is ambiguous.

### ISSUE THREAD

**Issue by sasori7** [ltdrdata/ComfyUI-Inspire-Pack#197]
in the example prompt text files, there isn't an example of how to use 'name'.
I expected that it would be the name of the file.  So, I converted 'save image' from text to input and plugged 'name' to it.
I formatted the text portion like this:
```
positive:3D image, a cute girl stands at full height holding a Map.

negative:text, logos

name:map
------------
```
this doesn't work.  It just names the image the filename containing the batch... which doesn't make sense.

**Comment by ltdrdata** [comment]
The name is not something set inside the prompt file.
It is used to return the filename of the prompt.

**Comment by sasori7** [comment]
Actually, I found a workaround:
I set the desired filename under _negative_:
like negative:boat
then, I plug that into the save image node.
this works as expected.
