### ISSUE TITLE
Openpose Preprocessor error in segs-controlnet.json example

### ISSUE THREAD

**Issue by vincetheeleventh** [ltdrdata/ComfyUI-Inspire-Pack#2]
Canny works great, but when switching to the OpenPose Preprocessors Provider (SEGS), an error occurs:

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/27981420/7952f068-7aa8-4a9d-b5a8-d4539c663c6a)

the example json:
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/27981420/60102102-d2ed-4570-bf73-798bd54f4f47)

**Comment by ltdrdata** [comment]
Could you please check if you are using the `old contolnet preprocessors` instead of `controlnet preprocessor aux`?

**Comment by vincetheeleventh** [comment]
Ah yes that fixed it. Much appreciated 🙏
