### ISSUE TITLE
how to get similar result like "effective block analyzer" in sd-webui by using lora block weight 

### ISSUE THREAD

**Issue by xiaohong23** [ltdrdata/ComfyUI-Inspire-Pack#20]
I used the xyplot for lora block weight and trying to get the similar result like "effective block analyzer" in sd-webui but never worked.  I guess the xyplot mode: diff or diff+heatmap is for this function.  When I switched to diff mode and changed A and B in different value, it just give me the same result as simple mode.  No comparison images and diff images, no error message either.  Do I need to do more to get the diff out?  thank you.

**Comment by ltdrdata** [comment]
Have you tried this workflow?

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/xyplot-lbw.json

**Comment by xiaohong23** [comment]
This is what I am looking for.  Thank you very much!
