### ISSUE TITLE
Value not in list: lora_name

### ISSUE THREAD

**Issue by lilly1987** [ltdrdata/ComfyUI-Inspire-Pack#201]
It uses the API method.
Because of the way the file is preloaded when the server starts,
when adding the lora file, it says that the file does not exist.
I don't want to restart the server every time I add a file.

```
Failed to validate prompt for output 26:
* LoraLoaderBlockWeight //Inspire LoraLoader-mika-imascgPDXL-01:
  - Value not in list: lora_name: '..\ComfyUI\models\loras\Pony\char\mika-imascgPDXL-01.safetensors' not in (list of length 4800)
* LoraLoaderBlockWeight //Inspire LoraLoader:
  - Value not in list: lora_name: '..\ComfyUI\models\loras\Pony\char\mika-imascgPDXL-01.safetensors' not in (list of length 4800)
```

### Loading: ComfyUI-Inspire-Pack (V1.2)

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/34b69e5f-b32d-4c18-b085-c5af249aa42c)
This is not an issue related to the Inspire Pack. It is an issue with ComfyUI itself, and updated information can be reloaded using the **refresh node definitions** function.

**Comment by prudhvi7780** [comment]
![Image](https://github.com/user-attachments/assets/73995155-f567-4512-89bf-145c743d8b18)
ERROR: PROMPT OUTPUTS FAILED VALIDATION
LoraLoaderModelOnly:
 - lora_name: 'WAN 2/Wan21_CausVid_14B_T2V_lora_rank32.safetensors' not in ['Wan21_CausVid_14B_T2V_lora_rank32.safetensors']: Value not in list
