### ISSUE TITLE
plz delete resources\lbw-preset.txt in github, every update will delete my edited lbw-preset.txt

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Inspire-Pack#21]
plz delete resources\lbw-preset.txt in github, every update will replace my edited lbw-preset.txt
(just give a readme let user create it himself ) or if you have another good idead

**Comment by ltdrdata** [comment]
You should not modify that file.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/LoraBlockWeight.md

**Comment by xueqing0622** [comment]
yes, it works!  Thx for your answer,
by the way, can you help me: some problem, but I don't know how to deal with it:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/95
