### ISSUE TITLE
When using MediaPipeFaceMeshDetectorProvider, it will cause 'FaceDetailerPipe' to occur an error

### ISSUE THREAD

**Issue by suede299** [ltdrdata/ComfyUI-Inspire-Pack#22]
ComfyUI stdout: Traceback (most recent call last):
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 152, in recursive_execute
ComfyUI stdout:     output_data, output_ui = get_output_data(obj, input_data_all)
ComfyUI stdout:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 82, in get_output_data
ComfyUI stdout:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
ComfyUI stdout:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 75, in map_node_over_list
ComfyUI stdout:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
ComfyUI stdout:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 975, in doit
ComfyUI stdout:     enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
ComfyUI stdout:                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 392, in enhance_face
ComfyUI stdout:     DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 217, in do_detail
ComfyUI stdout:     image_pil.paste(enhanced_pil, (seg.crop_region[0], seg.crop_region[1]), mask_pil)
ComfyUI stdout:   File "D:\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\PIL\Image.py", line 1713, in paste
ComfyUI stdout:     self.im.paste(im, box, mask.im)
ComfyUI stdout: ValueError: images do not match
------------------------------------------------------------------------------------------------------------------------
![屏幕截图 2023-10-08 160955](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/85022330/cd883b4d-a093-41e6-bd03-ca472e9ac83c)
Tried updating the nodes used. Switching the version of pillow. Changing FaceDetailer input images to different sizes.
Impact Pack version:4.12
img2texture 1.1.0
Pillow 10.0.1 & 0.9.5

**Comment by ltdrdata** [comment]
Sned me the workflow then I'll check it.

**Comment by suede299** [comment]
> Sned me the workflow then I'll check it.
[testworkflow.txt](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/12840857/testworkflow.txt)


Can't upload the json file, can only change the file name to .txt

**Comment by ltdrdata** [comment]
Oh, now I've finally checked the version information properly. Please update Impact Pack and ComfyUI to the latest versions for now.

**Comment by suede299** [comment]
> Oh, now I've finally checked the version information properly. Please update `Impact Pack` and `ComfyUI` to the latest versions for now.
> 
> I've confirmed that there are no issues with the above workflow in the latest version for now. Latest version is V4.16.5

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/85022330/b1b17f5b-bfb4-400d-8f9b-8ed630e7bbdb)
![屏幕截图 2023-10-08 232414](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/85022330/20544f19-2e4e-47d1-96e8-f743901018d9)
I just updated to latestversion, including the subpack that had commits today, and am getting the same error message.
Is it safe to assume it's a dependency package version issue?

**Comment by ltdrdata** [comment]
Oh. I produced through the attached image. Now, I'll digging it.

**Comment by ltdrdata** [comment]
This is fixed on `Impact Pack` V4.16.6.
