### ISSUE TITLE
Plz filter without  the <lora;**>  before output the conditioning in  WildCard Encode

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Inspire-Pack#31]
Plz filter without  the <lora;**>  before output the conditioning in  WildCard Encode,

I find remove and filter all the <lora;**> before output the conditioning can get the better Semantic understanding and better graphics effect

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/cb607f34-d9fa-4cd4-bc53-cca39af7050f)

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/f3c89104-b285-459f-b53f-3831ddcafbca)

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/5aa98c3f-d8fe-48ea-a09f-c091ce9190b3)

**Comment by xueqing0622** [comment]
When there is one lora, there is not much different, 
but when there are more than three loras, the different is a bit big, like my workflow, 3 loras is a bit difference. If add more lora, it can be more different.

This is just an assumption I made by connecting to workflow, but of course you'll have to test the kernel to see how it works.

**Comment by xueqing0622** [comment]
After update 
1 comfyui 
2 https://github.com/jags111/efficiency-nodes-comfyui (the main author doesn't update now)
3 https://github.com/ssitu/ComfyUI_restart_sampling
The graphic effect get better and the result between remove and keep all the <lora;**> before output the conditioning are small now  the high probability
Seems because Comfyui update the sample
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/e44c421c-a54b-4fc3-8f1c-6b0305afa4ce)
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/5f0ab404-2bf2-4587-ad92-9bed09c7cfd5)

**Comment by xueqing0622** [comment]
more test about 5 loras, and give prompt "(upper_body, dynamic_pose,:1.5)," more action
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/2ac99b1f-6057-4aa5-8404-c64d155f761e)
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/4417219a-0c53-4b23-9cb5-33776cf49f87)

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/21a19a9e-42b3-448e-bcb3-600430dc8821)

**Comment by ltdrdata** [comment]
I haven't found any other issues, except that when clip strength is omitted, it defaults to 1.0.

![wildcard](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/388d5f78-0beb-4287-bc57-60565d4347c0)
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/a0f92adf-9aea-4cdf-a09b-d9771ce4f57e)

**Comment by xueqing0622** [comment]
oh! Thx, that's cool, 
I'm relieved that you've answered my question.
