### ISSUE TITLE
Mask Seed Exploration Not Respecting Mask

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Inspire-Pack#32]
I am running a simple workflow based on your example, but have added in a variable to help keep the seeds aligned.  I am using a simple mask to find the face and then using the new regional seed to shift that. However, this does not appear to be working as expected.  Just sanity checking what I have here.  Workflow attachment in next comments.

**Comment by sedetweiler** [comment]
[workflow (41).json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/13336934/workflow.41.json)

**Comment by ltdrdata** [comment]
Here, I increased the threshold and applied strong strength after reducing the size of the face mask through erosion (negative dilation).

![seedexplorer](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/796880bb-6e28-45af-a4b8-d1dc6b91e637)

Controlling noise changes the direction of generation, but it doesn't meaning guarantee better result.

Using a regional seed allows you to set specific points where variations in noise occur, making it possible to control significant changes. This increases the likelihood of preserving the composition compared to changing the entire noise.

After conducting several experiments, it seems that the base model doesn't yield good results until the current facial composition changes.

![workflow (3)](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/15f5ac55-7b11-4a53-a587-48e1871064bb)

**Comment by sedetweiler** [comment]
Thank you for the clarification!  Cheers!

**Comment by sedetweiler** [comment]
Is it possible to see or control the heatmap of the changes centered around the region?  I always wanted this for the regional prompt as well, but not sure it is possible.  I really want a method to make some areas off-limits to change.

**Comment by ltdrdata** [comment]
> Is it possible to see or control the heatmap of the changes centered around the region? I always wanted this for the regional prompt as well, but not sure it is possible. I really want a method to make some areas off-limits to change.

This involves a somewhat complex technical issue. Starting from `EmptyLatent` has a significant impact on the entire image since denoise, from the initial stages, causes pixels in the image to mutually influence each other.

Therefore, the only viable option is to go with i2i. Additionally, clearing the mask area and starting over is, as you may understand, equivalent to performing inpaint fill.
