### ISSUE TITLE
Error occurred when executing LoadImagesFromDir //Inspire:

### ISSUE THREAD

**Issue by somebush** [ltdrdata/ComfyUI-Inspire-Pack#33]
`Directory 'F:\ai-ref\Openpose\poses cannot be found.'

  File "f:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "f:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "f:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\image_util.py", line 31, in load_images
    raise FileNotFoundError(f"Directory '{directory} cannot be found.'")`

Moving the folder to the ComfyUI directory and writing the path in the format you wrote in #17 does not help

**Comment by ltdrdata** [comment]
What is the directory and your input?

**Comment by somebush** [comment]
f:\AI\ComfyUI_windows_portable\ComfyUI\input\style1\

**Comment by ltdrdata** [comment]
> f:\AI\ComfyUI_windows_portable\ComfyUI\input\style1\

If you are running ComfyUI from `f:\AI\ComfyUI_windows_portable\`, then the parameter should be `input\style1`.

**Comment by somebush** [comment]
It is very strange. Now I paste the same path and did not get the error.

**Comment by somebush** [comment]
I understand. An error occurs when Batch Count is greater than 1.

**Comment by ltdrdata** [comment]
> I understand. An error occurs when Batch Count is greater than 1. Or maybe the fact is that the Primitive node produces random numbers that exceed the number of files in the folder.

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/4c0fa99d-baf3-4563-89fc-bfd90502bb3e)

Are you saying that you connected `image_load_cap` as a primitive node and set it to be 2 or more? `image_load_cap` can be any value greater than or equal to 1, so it shouldn't matter how large it is. Just be aware that if the start index is too large, it will result in an error because it won't be able to output any image.
