### ISSUE TITLE
Variation seed question

### ISSUE THREAD

**Issue by alenknight** [ltdrdata/ComfyUI-Inspire-Pack#34]
not an issue (sorry, not sure where to post this as it's more a question ) : 
 how do we check variation seed?  

i saw your tutorial on variation seed and the other one for explorting variation seeds.... but what if we want to find the exact seed and variation seed that was used prior? if i run a variation seed with the float, it'll run through images as expected... but it's generating multiple images each time.  is there a way to run JUST that seed/variation?  
i'm guessing through seed explorer and doing the calculations to reach it?  is there something built into inspire pack as a node that achieves this ?

love all the work you do, btw.  really awesome stuff.  and your web tutorials!  i saw folks mention the lack of voice, but with how much you do and churn these out... it totally makes sense you are getting out what you can and it's greatly appreciated.  insanely detailed and thorough!

**Comment by ltdrdata** [comment]
Here is an appropriate place not only for issues but also for receiving questions.

If you're mentioning generating multiple images while varying the `strength`, to explain the effect, you've modified the strength widget as an input and connected it with a float range. 

By default, it accepts only one input as widget value, generating a single image.
