### ISSUE TITLE
What is the reason despite installing the Inspire-Pack

### ISSUE THREAD

**Issue by HASAN3DG** [ltdrdata/ComfyUI-Inspire-Pack#35]
What is the reason despite installing the 
![Screenshot 2023-11-21 101606](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/74836845/b4e19006-dc33-4914-9365-9580669ad58c)
Inspire-Pack)

**Comment by ltdrdata** [comment]
Is your Inspire Pack up to date?
In that case, what message is displayed on terminal?

**Comment by HASAN3DG** [comment]
Thank you. I actually noticed that I was using an old version, which I deleted and used the new one... You are doing a wonderful job. Thank you with all my heart.
