### ISSUE TITLE
Plz add A111 mixed prompt [Cockapoo_ear:Chihuahua:0.3] and other Features like smzNode in wildcardEncode

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Inspire-Pack#37]
Plz add A111 mixed prompt [Cockapoo_ear:Chihuahua:0.3] and other Features like smzNode
https://github.com/shiimizu/ComfyUI_smZNodes
[Alternating words](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#alternating-words)
Weight normalization
Usage of BREAK and AND keywords
Optional embedding: identifier

this is different between wildcardEncode ,smzNode, bnk advanced  clip text encode
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/f78928d9-38f4-44b4-a90b-6d27541fcf25)

**Comment by ltdrdata** [comment]
Unfortunately, smZ_Nodes has a significantly different structure from the BNK node. Contrary to what is visible, there are also many hidden options. Therefore, it cannot be simply integrated into `Wildcard Inspire`. It must be used in its current form, utilizing `populated_text` as it is now.

**Comment by xueqing0622** [comment]
ok, I appreciate your reply.
