### ISSUE TITLE
Error occurred when executing ApplyRegionalIPAdapters //Inspire:

### ISSUE THREAD

**Issue by StartHua** [ltdrdata/ComfyUI-Inspire-Pack#38]
Error occurred when executing ApplyRegionalIPAdapters //Inspire:

Error(s) in loading state_dict for ImageProjModel:
size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1280]) from checkpoint, the shape in current model is torch.Size([8192, 1024]).

**Comment by ltdrdata** [comment]
Please check if the IPAdapter model, clip_vision model, and checkpoint model are not mixed with SDXL and SD1.5.
