### ISSUE TITLE
wildcardEncode (inspire pack) seed can't work for input

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Inspire-Pack#40]
wildcardEncode (inspire pack) seed can't work for input
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/114840118/1613829f-7e9e-432c-83a3-11e6b084f167)

He is either random or fixed before conversion, and does not change according to the node that flows in.

by the way Global seed (inspire pack) seems not work good at control_before_generate,.

**Comment by ltdrdata** [comment]
`Wildcard Encode` is a node that generates text populated before the prompt is executed, storing it in the workflow of the resulting image. Therefore, values generated during execution cannot be used. As a result, only primitive nodes are allowed for the seed.
