### ISSUE TITLE
GlobalSampler //Inspire?

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Inspire-Pack#46]
I use the GlobalSeed //Inspire node a lot and I love it!
Would it be possible to have the same for `sampler_name`/`scheduler`?

My use case is that I have a larger workflow with many samplers (~14) and sometimes want to test it with different samplers. Extracting as primitive works, but makes the workflow messier, especially since primitives have (had?) race condition bugs with reroutes.

GlobalSeed solves this beautifully for the seed, it would be great to have the same for the sampler/scheduler. Like with the seed, converting sampler_name/scheduler to input should prevent the replacement.

Thanks!

**Comment by ltdrdata** [comment]
Are you suggesting that you want to set a random `sampler_name/scheduler` for each sampler based on the seed?

**Comment by alexopus** [comment]
No, not random. A fixed value. Like what GlobaSeed does when action is 'fixed'. Basically a single node that controls all the sampler_names and schedules (which are not inputs).

GlobalSeed node inputs:
sampler_value: <list_of_samplers>
scheduler_value: <list_of_schedulers>

Randomization would be just a fun addition - I have no use case for it.

**Comment by ltdrdata** [comment]
> No, not random. A fixed value. Like what GlobaSeed does when action is 'fixed'. Basically a single node that controls all the sampler_names and schedules (which are not inputs).
> 
> GlobalSampler node inputs: sampler_value: <list_of_samplers> scheduler_value: <list_of_schedulers>
> 
> Randomization would be just a fun addition - I have no use case for it.

Are you trying to change the common value for the `sampler_name/scheduler` for all samplers?

**Comment by alexopus** [comment]
> Are you trying to change the common value for the `sampler_name/scheduler` for all samplers?

Yes, exactly.

**Comment by ltdrdata** [comment]
This is added on V0.54

**Comment by alexopus** [comment]
Thank you, tested it and it works nicely!

**Comment by alexopus** [comment]
I think there is an issue with the "exceptions".

In this example I am using dpmpp_sde/karras as global sampler/schaduler and make an exception for this sampler to use dpmpp_2m (Tiled KSampler doesn't work well with sde):
![dpmpp_2m](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/23327bf5-92d7-4a22-868b-150cc9bde97b)

To confirm I ran the same seed and let this sampler accept the global dpmpp_sde value:
![dpmpp_sde](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/76fcf72f-51b3-4e32-944b-b89112e2c49d)

You can see that the result is the same, meaning that this Sampler takes the global value, when it should stick to the input pimitive value.

Here is the full workflow to reproduce: 
[workflow.json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/13770671/workflow.json)

**Comment by ltdrdata** [comment]
This is fixed on V0.54.1
