### ISSUE TITLE
error:"ImportError: cannot import name 'utils' from 'libs' " after  fix: missing import of libs.utils

### ISSUE THREAD

**Issue by gtbloody** [ltdrdata/ComfyUI-Inspire-Pack#50]
I found that the code 'from libs import utils' was added in the files inspire/regional_nodes.py and inspire/segs_support.py. How can I install 'libs'?

**Comment by ltdrdata** [comment]
It is updated, recently. Update and retry.
And make sure latest ComfyUI-Manager, too.

**Comment by gtbloody** [comment]
I solved.
change [from libs import utils] into [from .libs import utils]
utils.py is in custom_nodes\ComfyUI-Inspire-Pack\inspire\libs
