### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by lunatico67** [ltdrdata/ComfyUI-Inspire-Pack#51]
![InspirePack](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/79542282/1cc9e9fb-59f8-45e3-a0b9-99f9403fa216)

**Comment by gtbloody** [comment]
change the codes [from libs import utils] into [from .libs import utils](add an '.' ) in files inspire/regional_nodes.py and inspire/segs_support.py

**Comment by GoDJr** [comment]
I’m also getting a import fail, terminal says  [ModuleNot FoundError : No module named 'lib'](https://stackoverflow.com/questions/57328142/modulenot-founderror-no-module-named-lib)

**Comment by ltdrdata** [comment]
> ![InspirePack](https://private-user-images.githubusercontent.com/79542282/293303369-1cc9e9fb-59f8-45e3-a0b9-99f9403fa216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjA2OTEsIm5iZiI6MTcwMzgyMDM5MSwicGF0aCI6Ii83OTU0MjI4Mi8yOTMzMDMzNjktMWNjOWU5ZmItNTlmOC00NWUzLWEwYjktOTlmOTQwM2ZhMjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAzMjYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZTViM2JiN2ZhMjNkNThmZTgxM2YzYjg4ZDkzYWZhZDRhMmFlNGIwM2RiYzEzODJkMTVlODY1MzhhZTg3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDS5pIwLDFdfpLvwDP_UQe-8OoUwbjNMuW5EJP4LsbE)

Update Inspire Pack to latest version. Still error is persistent. Show me the startup full log. `comfyui.log`

**Comment by GoDJr** [comment]
I updated to the latest version im still getting the following error: 
### Loading: ComfyUI-Inspire-Pack (V0.54.2)
Traceback (most recent call last):
  File "/home/sagar/ComfyUI/nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sagar/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/__init__.py", line 30, in <module>
    imported_module = importlib.import_module(".inspire.{}".format(module_name), __name__)
  File "/home/sagar/miniconda3/envs/comfy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sagar/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack/inspire/segs_support.py", line 4, in <module>
    from libs import utils
ModuleNotFoundError: No module named 'libs'


here is the comfyui log 
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/13790742/comfyui.log)

**Comment by gtbloody** [comment]
> > ![InspirePack](https://private-user-images.githubusercontent.com/79542282/293303369-1cc9e9fb-59f8-45e3-a0b9-99f9403fa216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjA2OTEsIm5iZiI6MTcwMzgyMDM5MSwicGF0aCI6Ii83OTU0MjI4Mi8yOTMzMDMzNjktMWNjOWU5ZmItNTlmOC00NWUzLWEwYjktOTlmOTQwM2ZhMjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAzMjYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZTViM2JiN2ZhMjNkNThmZTgxM2YzYjg4ZDkzYWZhZDRhMmFlNGIwM2RiYzEzODJkMTVlODY1MzhhZTg3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDS5pIwLDFdfpLvwDP_UQe-8OoUwbjNMuW5EJP4LsbE)
> 
> Update Inspire Pack to latest version. Still error is persistent. Show me the startup full log. `comfyui.log`

<img width="525" alt="image" src="https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/130019359/03d65bf4-1798-4e05-bd9a-e30a29f66f49">
<img width="772" alt="image" src="https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/130019359/81b6664f-f3a3-40f5-ac06-95f80c669e8d">
The code here may need to be changed to use relative paths
<img width="1016" alt="image" src="https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/130019359/0e0f081d-2b50-4f5b-9198-134a0e44271e">

**Comment by GoDJr** [comment]
I did what gtbloody recommended and it worked perfectly

**Comment by ltdrdata** [comment]
oops... I'd mis patched before.. Update again.

**Comment by lunatico67** [comment]
A lot of thanks!  With the last update works perfect!
