### ISSUE TITLE
I'm unclear how to save the 'zipped' metadata

### ISSUE THREAD

**Issue by RikkB** [ltdrdata/ComfyUI-Inspire-Pack#52]
What node actually writes out the 'zipped' metadata?  Is the Zip Prompt node supposed to connect to the Bind [Image List...] and then the Bind node saves the file?  If so, I don't seem to understand how that works.

Apologies for the simplistic question

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/276b9dbd-8e45-493b-a464-d9b32654ccb0)

ZIPPED_PROMPT is not intended for saving purposes; rather, it is meant for retrieving information from a prompt for use.
