### ISSUE TITLE
Feature Request: the faceidv2 ipadapter

### ISSUE THREAD

**Issue by agawrylak** [ltdrdata/ComfyUI-Inspire-Pack#56]
since it uses a new node, I do not think it works with regional ipadapter. Could that be added?

**Comment by ltdrdata** [comment]
I'll add this.

**Comment by agawrylak** [comment]
Thank you kindly sir!
Could I also ask you - what's the difference between using regional ipadapter and just a normal ipdapater with attention mask? For some reason regional seems to work better

**Comment by ltdrdata** [comment]
> Thank you kindly sir! Could I also ask you - what's the difference between using regional ipadapter and just a normal ipdapater with attention mask? For some reason regional seems to work better

The regional IPAdapter is nothing more than a wrapper node designed for the convenient regional application of the IPAdapter. Internally, it utilizes the IPAdapter.

**Comment by ltdrdata** [comment]
This is updated
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-ipadapter-faceid.png
