### ISSUE TITLE
Regional Seed doesn't seem to work with some model.

### ISSUE THREAD

**Issue by boonyasukd** [ltdrdata/ComfyUI-Inspire-Pack#59]
On my current machine, I'm using Dreamshaper XL Turbo. I downloaded your example `png` file, and tried out the workflow on my local machine. The change doesn't seem to limited to any particular region, and the change is rather subtle, almost as if there wasn't any noise being injected. 

From the workflow, it seems you are using a non-turbo SDXL. It's a bit big to download for my part, so I would like to get a confirmation from you instead that this feature actually doesn't work on every kind of model. Stating that in a README would be fine.

Thank you.

**Comment by ltdrdata** [comment]
The seed only affects the initial noise configuration. It is unrelated to the model.

**Comment by boonyasukd** [comment]
I have other models on hand, so I did a bit of experimenting. The result is rather interesting, to say the least... It'd be great if you can guide me what I need to do to proceed.

- For the record, I'm using `dreamshaper_8.safetensors`. I believe this is the SD1.5 version.
- The person in the original image is missing a limb, so I made a small masking dot where the limb should be.
![Screenshot 2024-01-24 165800](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/8109816/fbe28289-da44-4111-b5dc-7688aeb0e789)

- Then I added the strength of `0.01`.
![Screenshot 2024-01-24 165916](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/8109816/925bfa57-5829-45ee-a983-88085ad56ba5)

- And I got this result. Injecting additional strength seems to affect the whole image instead of being localized to a particular region:
![Screenshot 2024-01-24 165945](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/8109816/5dfa7a18-cfc0-4a8e-ad1f-fbb15eaf35b6)

**Comment by ltdrdata** [comment]
The regional seed only changes the noise; it is not an inpaint.
It changes the local initial state to alter the direction of image generation.

And the masked region is only applied to the place where noise is changed; it is not applied to the diffusion process, so the areas affected by this noise are the entire image. It simply has the most significant impact at the origin.
