### ISSUE TITLE
Lora Block Weight Node not working

### ISSUE THREAD

**Issue by var1ableX** [ltdrdata/ComfyUI-Inspire-Pack#6]
I followed the youtube window example (https://youtu.be/X9v0xQrInn8). What I found was the Block Weight Node doesn’t seem to be loading the Lora and I ended up with the same 3 images recurring no matter which blocks we being activated in either scenario NONE, ALL, MIDD or FULL TEST 17.

E.g.:
Model: Henmix_Real_v40
Lora: edgKM

**Comment by ltdrdata** [comment]
Upon inspection, it appears that there is a bug in the `XY Plot` processing of the current `Efficient Loader` node, causing accumulation. I will submit a PR to address this issue and have it fixed.

**Comment by var1ableX** [comment]
> Upon inspection, it appears that there is a bug in the `XY Plot` processing of the current `Efficient Loader` node, causing accumulation. I will submit a PR to address this issue and have it fixed.
> 
> Result should be like this. ![ComfyUI_temp_nyztj_00005_](https://user-images.githubusercontent.com/128333288/267537434-1410fe34-96b5-4863-923c-b94ca87f1788.png)
> 
> [LucianoCirino/efficiency-nodes-comfyui#172](https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/172)

Thanks a lot for looking into this and confirming and running the test!

**Comment by ltdrdata** [comment]
This PR is merged an hour ago. Update Efficient Nodes to latest version.
