### ISSUE TITLE
Broadcast Error

### ISSUE THREAD

**Issue by gisu** [ltdrdata/ComfyUI-Inspire-Pack#60]
I have tried to install the IPAdapter Helper, but I get broadcast errors. It doesn't matter whether I connect all outputs or just one (like the model in the screenshot). According to the console, the error comes from the Everywhere Nodes, which have no problems without connecting the Helper Node.

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/442468/2bf65055-ba2f-45ed-abb3-eb307af2ac68)

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/442468/5430f64b-3032-48cb-a877-7eda7d95763c)

**Comment by ltdrdata** [comment]
This is an issue with "Use Everywhere."
https://github.com/chrisgoringe/cg-use-everywhere/issues
