### ISSUE TITLE
GlobalSeed 'Seed' Error

### ISSUE THREAD

**Issue by Malbathla** [ltdrdata/ComfyUI-Inspire-Pack#61]
While running my workflow I noticed the GlobalSeed was red highlighted and the console showing 

ERROR:root:Failed to validate prompt for output 112:
ERROR:root:* (prompt):
ERROR:root:  - Value 804822466654819 bigger than max of 4294967295: value
ERROR:root:* GlobalSeed //Inspire 112:
ERROR:root:  - Value 804822466654819 bigger than max of 4294967295: value
ERROR:root:Output will be ignored

(Yes I pasted the Big seed from a KSampler)

Checking I was fully up to date I saw that in the last few days you have set the max seed for Inspire to be 2\*\*32-1 (the 4294967295 above) however Comfy's own KSamplers uses 2**63-1

If this greatly reduced max seed intentional? as it seems to be limitting the scope of the GlobalSeed overall

Note: manually pasting/adding seeds above the max setting of 2**32-1 is still used and populated to all Samplers etc in the workflow however you can't just click the arrows? to inc/dec the seed if it exceeds the max above.

**Comment by ltdrdata** [comment]
Some seed widgets were restricted to `2**32 - 1` because they only allowed that limit. The maximum allowable value has been increased back to its original. However, random values will only be generated within the range of `2**32 - 1`.
