### ISSUE TITLE
Node request: Remove ControlNet from Regional Prompt

### ISSUE THREAD

**Issue by Bocian-1** [ltdrdata/ComfyUI-Inspire-Pack#63]
I would like to request a node to remove ControlNet from regional prompts

I'm working on a workflow where I can chain an arbitrary number of regional prompts and requires ControlNet in 1st pass, but afterwards, as long as denoising is kept low, it is no longer necessary and needlessly extends generation times. Your Remove ControlNet node is already a godsend in similar cases, but when working on regional prompts I have to create 2 sets of them, one with and the other without ControlNet since there is no way to remove it after making the regional prompt. 

This also means that if I want to sync samplers and schedulers between all regional prompts, it leads to additional connections as only primitive nodes can be attached to those inputs and rerouting primitives isn't supported
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/70019596/5e06ce56-7f93-41a0-9bd4-fa9f55d1d9cb)
It would also be nice to have a way to set those two (sampler and scheduler) remotely without using primitives so they can be rerouted and chained between grouped nodes like other inputs in above screenshot but I'd be more than happy with just a Remove ControlNet node :)

**Comment by ltdrdata** [comment]
This is added.
You need to update both Inspire Pack/Impact Pack.
