### ISSUE TITLE
Bug or feature? Wrong seed is saved with global seed node!

### ISSUE THREAD

**Issue by dxdpxl** [ltdrdata/ComfyUI-Inspire-Pack#64]
Hi. First, I thought I just changed to much and that's why a seed from an actual image isn't working or at least will not give me the same result. Then I tested it multiple times and even if everything is the same (model, lora, prompt etc.) I can't get the image back with the seed it was saved. It drove me nuts...

But then I found out, that Global Seed (Inspire) "forwards" the seed from the previous image to the current image, which is then getting saved via "Save Image", always with the seed from the previous image. So, if I want to replicate an image, I need the seed from the previous image. Is this wanted or a bug? This makes this node (at least for me) totally useless, because I could never replicate the same image from this seed.

But I love the option to automatically have the same seed on any sampler... Is there a way to change or fix is? Btw. I use the Global Seed (Inspire) with Efficiency Nodes, but also tested it with the default workflow from ComfyUI and just put a Global Seed node into. It happens in both setups! Very simple workflows are below if needed.

[seed-save-test-default.json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/14150883/seed-save-test-default.json)
[seed-save-test-efficiency-nodes.json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/14150884/seed-save-test-efficiency-nodes.json)

**Comment by ltdrdata** [comment]
Oh there was a bug. I just fixed.

**Comment by dxdpxl** [comment]
Yeah, and an big error on my side. Sry! I tried to catch the seed from the KSampler which can't ofc not work, stupid me, lol. Just found this out 30 seconds before the email from github popped up with your message...

Solution. After I renamed the Global Seed (Inspire) node (Node name for S&R) in property panel to GSI (to get rid of the spaces) and then catching the (.value) ... voila it saves the right seed to the image, and ONLY then.

Example for [Save Image]: filename_prefix: %date:yyyy-MM-dd%/%date:hh-mm-ss%_%GSI.value%

Btw... Even after your update, the Global Seed node does not forward the seed through the other nodes for correct saving... Don't know how to further explain this... Just I tested it again, before I post the above solution, if someone else comes across this problem.

AND ofc thanks for updating...

**Comment by dxdpxl** [comment]
UPDATE: I was wrong again... SORRY for the total confusion!

Even the above solution barely helps. After making multiple images per batch with randomized seeds, it again uses the last_seed from the Global Seed node for saving, not the actual seed, even if I directly catch the seed (value) from the node and it looks like it happens in all modes (action) except fixed... if I set it to fixed and increment or decrement by hand, it saves the seed correct, but if I switch back to randomize or any other action, it uses the last number from the fixed one for saving and then again always the seed from the previous randomized image.

Maybe that info helps... Yeah I'm also totally confused now, lol 😂

**Comment by ltdrdata** [comment]
To clarify, if the `Global Seed` is not muted, all seeds are controlled by the Global Seed. The specific seed values of other nodes are not practically significant.

The reproduction of image generation is entirely controlled by the `Global Seed`. Previously, there was a bug where the value of the `Global Seed` was incorrectly stored in the workflow of the generated image.

There was an issue where the stored workflow did not consider the differences between `control after generate` and `control before generate`, causing inconsistent saving. This issue has now been resolved.

When loading the saved image workflow, it should be possible to reproduce it exactly as it was saved.

**Comment by dxdpxl** [comment]
Yes, I understood the workflow. It's solved now!

I manually deleted the inspire pack and reinstalled it via manager. If I now catch the value for Save Image directly from the Global Seed node value and set the mode to control_after_generate, it works like it should and seems to always saves the right seed to the img. Looks like it didn't update properly. I apologize! THANK YOU for the patience! 🤓

Can be closed now!
