### ISSUE TITLE
[Feature Request] FaceKeypointsPreprocessor for InstantID

### ISSUE THREAD

**Issue by nomadoor** [ltdrdata/ComfyUI-Inspire-Pack#69]
[ComfyUI InstantID](https://github.com/cubiq/ComfyUI_InstantID)

It seems that InstantID and Detailer are very compatible, so we would appreciate it if you could implement it!
Thank you

**Comment by nomadoor** [comment]
I apologize, I didn’t fully understand ControlNetApply (SEGS). 
So, I should input the processed image into control_image, is that correct?

I will share the workflow of face swap for reference.
I believe it’s probably working correctly.
![Detailer_InstantID](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/124905471/0bdc282c-eb06-4757-9003-7e988e077a24)
[Detailer_InstantID.json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/14305626/Detailer_InstantID.json)

**Comment by ltdrdata** [comment]
That is correct workflow.

**Comment by nomadoor** [comment]
It seems better to set the guide_size to 1024 for InstantID as it uses the SDXL model. It’s working very well with this setting!
Thank you for your always wonderful work!
