### ISSUE TITLE
Lora Block Weights

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Inspire-Pack#7]
When doing the testing, should the first block always be 1?  Is that representing the base?

B1:**A**,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B2:**0**,A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B3:**0**,0,A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
B4:**0**,0,0,A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

**Comment by ltdrdata** [comment]
That's correct. The first block is the base block. This block is primarily responsible for determining all blocks except in, mid, and out.

Usually, there are no other blocks outside of the clip block, so the impact is limited.

ps: 
For a while, there has been an issue with the accumulation of model transformations in the XY Plot of Efficient Nodes. So, if you are testing with XY Plot, please update Efficient Nodes.

**Comment by ltdrdata** [comment]
OMG... I am watching your live... 
It seems your Efficient Nodes isn't updated...

In older versions, there is a bug in `Efficient Nodes`, causing an issue where the front-end model transformations accumulate in XYPlot. Therefore, it becomes progressively worse as you go further back.

**Comment by sedetweiler** [comment]
Thank you.  All good now.
