### ISSUE TITLE
Variation seed questions.

### ISSUE THREAD

**Issue by gachapengames** [ltdrdata/ComfyUI-Inspire-Pack#70]
Hello. Thank you for the nodes. I have a few questions related to variation seeds, some aren't specific to your nodes.

1. How can variations from a batch be regenerated by themselves? Do the batch generations now have a 3rd seed? (Initial seed, Variation seed, Variation-Variation seed? Or is the only way to ever regenerate them to run the entire batch again with exact same parameters?

2. Are variations of variations possible?

3. Do numbers weights like .015 work or only .01 .02 etc? Lower decimals can be entered, but comfyui still displays the rounded numbers, so which is actually being sent to sampler?

4. Do variation seeds reduce generation quality?

5. What is a recommended way to view the variation seeds from a generated image without loading the entire workflow? Utilities like "stable-diffusion-prompt-reader" do not show any of this data.

**Comment by ltdrdata** [comment]
1. Variation seed is fixed value. batch doesn't change variation seed. 
2. See seed explorer: https://www.youtube.com/watch?v=jE027ZRLKsI
3. The rounded value is sent to backend
4. Nope. It only affect to initial noise state.
5. Just see the `variation seed` since it is fixed
