### ISSUE TITLE
Bug in FromIPAdapterPipe

### ISSUE THREAD

**Issue by alexjx** [ltdrdata/ComfyUI-Inspire-Pack#74]
It seems there is a typo in FromIPAdapterPipe, the `RETURN_TYPES` has duplicated. I think the second `RETURN_TYPES` should be `RETURN_NAMES`

https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/3b501e2f799d95afd4c832024fc7861d5281d59e/inspire/regional_nodes.py#L197-L198

**Comment by ltdrdata** [comment]
oops... this is fixed.
