### ISSUE TITLE
[Feature request] Float range + Ksampler processing more than 1 image.

### ISSUE THREAD

**Issue by Cedri4** [ltdrdata/ComfyUI-Inspire-Pack#75]
Hi, I have been experimenting with float ranges and KSampler, and I realize that I can't use a float range with a KSampler when doing more than 1 image.
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/93396286/292d23f6-9934-455a-9c14-83835fa89778)
![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/93396286/e0b48eed-6f08-44e8-beba-0a3542196bb2)

Could you please add the functionality to make it work with batch processing on the KSampler? 

EDIT: I am using the KSampler from the inspire pack

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by Cedri4** [comment]
Somehow I fixed it by converting the group node into nodes, which makes it work.
