### ISSUE TITLE
IPAdapter Model Helper (Inspire)  error

### ISSUE THREAD

**Issue by KennyChan3389** [ltdrdata/ComfyUI-Inspire-Pack#76]
不知道您是否看得懂中文，但我不会英文，所以只能这么留言，该问题困扰我两天了。也检查了包括Python依赖包，IPA模型的位置和命名。ipa原生节点是能运行的。
<img width="910" alt="%7BA3BDC97E-2A3F-40f2-B71B-7AED3E8ECF02%7D" src="https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/155774773/aa6fadb4-28fc-43e4-a428-37528ed7de88">
希望给予解答，谢谢！

**Comment by ltdrdata** [comment]
You don't have proper clip_vision model.
