### ISSUE TITLE
Make Tile SEGS request/questions

### ISSUE THREAD

**Issue by lingondricka2** [ltdrdata/ComfyUI-Inspire-Pack#79]
Question 1: If I want an SDXL model to have the optimal number of pixels to work with, should bbox_size be 1024 or the resulting crop region be 1024?

Question 2: What does filter_segs_dilation do? Does not seem to do anything.

Request 1: Can you make min_overlap a percentage of crop region? that way you don't have to change it every time you change bbox_size and crop_factor. 

It's a bit finicky, you have to study the preview node each time to see if the tiles are overlapping, maybe even better would be code that makes sure there are no gaps between the tiles even with mask_irregularity at 1.0

Request 2: Have crop region as input instead of bbox_size depending on the answer to question 1.

**Comment by ltdrdata** [comment]
Answer 1: The reference should be the `crop_region`. Simply put, working with lower denoise on i2i is structurally more stable than with higher denoise on t2i, allowing for higher resolution, that's all.

Answer 2: It serves the purpose of dilating the masks of the input segs, either through filter_in_segs or filter_out_segs.

Req 1. Masks that become irregular due to mask_irregularity should form outside the mask bbox, and if the overlap factor is greater than 0, there should be no gaps between masks as normal.

Req 2. Conversely, if the crop region becomes the reference, ensuring overlap cannot be guaranteed.

**Comment by lingondricka2** [comment]
I don't fully understand your answer about overlap, I mean there are gaps unless you specify a really high min_overlap, even worse with mask_irregularity.
![Untitled](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/155384738/3fc7727c-c5d3-40f3-9b03-043f1c8ab6bc)
The image is 2048x2048, it should be 3x3 tiles even with min_overlap at 1 no? I have to set to 400 for no gaps.
[workflow (91).json](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/files/14468919/workflow.91.json)

**Comment by lingondricka2** [comment]
Oops didn't realize I posted this in the Inspire repo, oh well same author so it worked out ok :)

**Comment by lingondricka2** [comment]
Line 1443 and 1444 in segs_nodes.py seems wonky

```
if bbox_size <= 2*min_overlap:
            new_min_overlap = 2 / bbox_size
```

Should be?

```
if bbox_size >= 2*min_overlap:
            new_min_overlap = bbox_size / 2
```

**Comment by ltdrdata** [comment]
> Line 1443 and 1444 in segs_nodes.py seems wonky
> 
> ```
> if bbox_size <= 2*min_overlap:
>             new_min_overlap = 2 / bbox_size
> ```
> 
> Should be?
> 
> ```
> if bbox_size >= 2*min_overlap:
>             new_min_overlap = bbox_size / 2
> ```

It assumes overlap from both sides of the bbox. If the bbox is smaller than overlapping it from both sides, it means the overlap size is excessive.

But there is a mistake. That should be.

```
if bbox_size <= 2*min_overlap:
            new_min_overlap = bbox_size / 2
```

**Comment by lingondricka2** [comment]
I see, that printf confused me, so it should probably also be changed.

`print(f"[MakeTileSEGS] min_overlap should be greater than bbox_size. (value changed: {min_overlap} => {new_min_overlap})")`

**Comment by ltdrdata** [comment]
I confirmed that for irregular masks, the irregular part is implemented to be formed inside the mask rather than outside.
That need to be fixed.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/9c1d4eec46f9614bfc65680dc5467ff67f64548b

This fixed Make Tile SEGS, too.
