### ISSUE TITLE
GlobalSeed: is not effective when some nodes are muted or bypassed

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Inspire-Pack#8]
When some nodes are muted and/or bypassed, GlobalSeed does not replace the seed in any of the nodes.

Here is an example workflow:

![workflow](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/37832832-e5b8-479e-9e52-e2b761588c60)

In some cases the workflow won't execute at all, but I cannot reproduce that anymore rn...

**Comment by ltdrdata** [comment]
This is fixed on 3fb0d7825b67dccc822fecfac2648c48fec7bc88

**Comment by alexopus** [comment]
Thank you ❤️
