### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xpluscal** [ltdrdata/ComfyUI-Inspire-Pack#81]
Heya, getting this error, any ideas what this could be?

<img width="888" alt="Screenshot 2024-03-06 at 17 18 12" src="https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/3706722/44f2712c-9b21-480f-958d-1e056aece682">

Using this workflow:
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-ipadapter.png

**Comment by ltdrdata** [comment]
https://www.youtube.com/watch?v=FeeIHjt64SY

Make sure used models are downloaded properly.
