### ISSUE TITLE
IndexError: list index out of range from Retrieve Backend Data node

### ISSUE THREAD

**Issue by Davikar** [ltdrdata/ComfyUI-Inspire-Pack#82]
Getting this error when using the retrieve backend data nodes, the optimizations by rgthree are disabled, so they shouldn't affect the final result as far as I understand (the arguments are passed as is).
This error always pops up when I've run through a few workflows and freezes the entire ComfyUI instance.
The only cache key that is being updated between the workflows is a key that contains a context node (containing the latents and an image).

```
Exception in thread Thread-14 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "C:\AI\ComfyUI\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 209, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 364, in execute
    recursive_output_delete_if_changed(prompt, self.old_prompt, self.outputs, x)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 232, in recursive_output_delete_if_changed
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 26, in get_input_data
    obj = outputs[input_unique_id][output_index]
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
```

(It doesn't seem to help to change the key name between the workflows).

**Comment by Davikar** [comment]
I was using the Cache Backend Data List node, as I assume the rgthree context nodes output a list, but I've changed my workflow to save latents and images to separate non-list cache nodes and I haven't had any issues since. So I don't know if this is a bug or if I was just using the wrong kind of cache node?

**Comment by ltdrdata** [comment]
I'm not sure about the exact involvement of rgthree, so I can't say. However, the `Cache Backend Data List` aggregates the inputs being passed and caches them, while the `RetrieveBackendData` outputs in the form of a list if the input is a list.

And when using the caching feature, always be mindful of whether retrieval occurs before caching to avoid any issues with the execution order.

**Comment by Davikar** [comment]
This is the output from a context node:

`{'model': <comfy.model_patcher.ModelPatcher object at 0x000001AA22886850>, 'clip': <comfy.sd.CLIP object at 0x000001AA226D33D0>, 'vae': None, 'positive': None, 'negative': None, 'latent': None, 'images': None, 'seed': None, 'steps': None, 'step_refiner': None, 'cfg': None, 'ckpt_name': None, 'sampler': None, 'scheduler': None, 'clip_width': None, 'clip_height': None, 'text_pos_g': None, 'text_pos_l': None, 'text_neg_g': None, 'text_neg_l': None, 'mask': None, 'control_net': None}`

I think it's pretty much the same as a pipe from your pipe nodes.
Or is it better to use a normal backend cache node than a list version for this kind of output?

**Comment by ltdrdata** [comment]
> This is the output from a context node:
> 
> `{'model': <comfy.model_patcher.ModelPatcher object at 0x000001AA22886850>, 'clip': <comfy.sd.CLIP object at 0x000001AA226D33D0>, 'vae': None, 'positive': None, 'negative': None, 'latent': None, 'images': None, 'seed': None, 'steps': None, 'step_refiner': None, 'cfg': None, 'ckpt_name': None, 'sampler': None, 'scheduler': None, 'clip_width': None, 'clip_height': None, 'text_pos_g': None, 'text_pos_l': None, 'text_neg_g': None, 'text_neg_l': None, 'mask': None, 'control_net': None}`
> 
> I think it's pretty much the same as a pipe from your pipe nodes. Or is it better to use a normal backend cache node than a list version for this kind of output?

Combining such diverse data into one cannot be represented as a list. Lists are structures designed to iterate over data of the same type.

For such data, it's appropriate to cache and retrieve the entire set as a single value. Of course, nodes connected to retrieve from the cache should be capable of handling that value accurately.

The basic_pipe generated by ToBasicPipe always has a fixed structure, so it can be stored in the backend cache and connected to all basic_pipe inputs for use.

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/128333288/aa4cbdef-6387-4bf7-bec7-edd3ca18eddc)
