### ISSUE TITLE
GlobalSeed is not set correctly on a loaded workflow.

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Inspire-Pack#84]
In the following workflow, the sampler seed is `44873720`, which was generated by the GlobalSeed in the original run. GlobalSeed action was set to `randomize` and mode to `control_before_generate`:
![ComfyUI_00008_44873720](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/25933468/97719d08-9b57-4d00-ab53-0da472c2cf60)

But when loading this workflow from this image/json, although the sampler still has the same seed `44873720`, the GlobalSeed node shows a different value - `14517457`. I believe this has changed recently - before the GlobalSeed node would maintain the original seed value and it would be enough to set action to "fixed" in order to reproduce the image. But now, in order to reproduce, one has to change action to fixed **and** copy the seed from sampler to the GlobalSeed's value.

It actually seems that on load the seed value in GlobalSeed takes the `last_seed` of the original workflow. Which is not very useful, as it would not reproduce the image the workflow was loaded from either.

Is this a bug? I expect the loaded workflow to reflect the state it was saved in. In this case with the `44873720` in the value for the GlobalSeed. Or am I missing something?

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by alexopus** [comment]
Thanks! Indeed, pics generated after update set seed value correctly (and the action as fixed as bonus). However, old pics still load incorrectly, I guess there is nothing that can be done about that?

Minor nitpick though. The loaded image incorrectly sets the `last_seed` of GlobalSeed node. The value is not the one of that particular generation, but seemingly of the image *before* that. Example:

gen1: seed 1, last_seed: 0
gen2: seed 2, last_seed: 1

If I load gen2 image into comfy, seed is set to 2, and last_seed to 0 (which should be 1). At least this is the case for randomize action.

Not a big deal, of course. But would be nice to have it consistent.

**Comment by ltdrdata** [comment]
now last_seed will be stored properly.
