### ISSUE TITLE
GlobalSeed is burning my upscales :)

### ISSUE THREAD

**Issue by var1ableX** [ltdrdata/ComfyUI-Inspire-Pack#85]
Ok, this is not really a bug more of a feature request, however, none of the global seed solutions cater for the following Ux:

As a user I would like the option to "fix" a seed so I can upscale it, without having to bypass / mute nodes. However, I would like the upscale nodes to use seeds that are different from each other and the base. Otherwise, my upscales, esp. ones that feature multiple ultimate upscalers in a chain end up burning the final result substantially because they're using the same seed.

The closest I can get to this experience is setting something "increment/decrement for all nodes". However, this would also increment the seed for the base render that I'm trying to upscale.

Request:
- Wired Output (new): Add a INT output for the global seed node and a separate dropdown for this INT output (fixed, increment, decrement, random)
- Broadcast Output (existing): works as it does now

Ux:
- User can wire the base renderer to the new wired output and set it to fixed if they wish
- Non connected nodes are set by the existing "Broadcast" functionality

**Comment by ltdrdata** [comment]
When chained to sampling nodes of the same resolution, it seems appropriate to convert the seed into an input and connect it to the primitive node, thus excluding it from the global seed.
