### ISSUE TITLE
TypeError when using IPAdapterModelHelper to load InsightFace into cache

### ISSUE THREAD

**Issue by ozbayb** [ltdrdata/ComfyUI-Inspire-Pack#89]
Title: TypeError in __setitem__ method of TaggedCache class

Description:

In the __setitem__ method of the TaggedCache class (utils.py, lines 192-232), the tag variable is expected to be a string. However, it seems that in some cases, tag could be a boolean. This leads to a TypeError when the code tries to execute the line 'ckpt' in tag (line 220), because the in operation is not valid for boolean values.

This issue seems to have been introduced in a change to utils.py where the code now checks if 'ckpt' is in tag. If tag is not a string, this code fails.

Steps to reproduce:

Run a workflow with the IpAdapterModelHelper node set up to supply an InsightFace model to an IpAdapterApplyFaceID node.

Expected behavior:

The __setitem__ method should be able to handle any valid input without raising an error.

Actual behavior:

When tag is a boolean, the __setitem__ method raises a TypeError. This happens particularly when calling for loading the InsightFace model into the cache.

Possible solution:

Before checking if 'ckpt' is in tag, the code could check if tag is a string.

**Comment by ltdrdata** [comment]
This is fixed.
