### ISSUE TITLE
Load Image Batch From Directory

### ISSUE THREAD

**Issue by Torcelllo** [ltdrdata/ComfyUI-Inspire-Pack#95]
When I first used it, if I specified 6 photos
as Image Load Cap, ComfyUI would work
its way thru the whole 6 - one at a time.

Recently, it does not increment, and stays
static on whatever the start index image
happens to be!

Win 10, 64Gb Ram, 8Gb VRAM
Up-to-Date INSPIRE Node

**Comment by ltdrdata** [comment]
Could it be confusion between `Load Image List From Dir`? `Batch` processes all at once, while handling them one by one is a `List`.

**Comment by Torcelllo** [comment]
Load Image List loads all 6/uses all 6 photos in one go.
Just last week, Load Image Batch from Directory
went thru each photo one by one; but today its stalls
at the first photo of the batch only!

**Comment by Torcelllo** [comment]
Oops, my mistake, Load List is the one!!!
