### ISSUE TITLE
Face Detailer keeps failing on faces

### ISSUE THREAD

**Issue by gonzalu** [ltdrdata/ComfyUI-Inspire-Pack#96]
I am having trouble getting FACE to detect and refine... Eyes and Mouth work fine... 

Thanks for any help you can give me ...

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/32348862/0d566824-6a97-423f-8d8b-6e691cf6003f)

**Comment by gonzalu** [comment]
Thank you... I will follow your tips :D

**Comment by gonzalu** [comment]
I think my problem was mainly due to the size of the input image. Above a certain size, the detectors have a hard time detecting... so for now switching to smaller input images for detailing is working better. 

What is the upper limit I should be aware of ? 
Thank you.

**Comment by ltdrdata** [comment]
> I think my problem was mainly due to the size of the input image. Above a certain size, the detectors have a hard time detecting... so for now switching to smaller input images for detailing is working better.
> 
> What is the upper limit I should be aware of ? Thank you.

If the mask is shown in the mask preview, it means it has not failed to detect. The detailing was skipped because it exceeded the guide size (or max size).
