### ISSUE TITLE
MediaPipeFaceMesh Detector Provider not detecting in some instances

### ISSUE THREAD

**Issue by gonzalu** [ltdrdata/ComfyUI-Inspire-Pack#98]
I keep having a random problem with some images not being properly detected by this node. 

Any tips or advice as to why? Sometimes it works great sometimes it does not work. When it doesn;t work, the Ultralytics one works well. 

Ultralytics 

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/32348862/35710ad2-5975-43dc-8ec5-f43a7f320370)

MediaPipeFaceMesh Detector Provider 

![image](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/assets/32348862/8fea150d-9045-4dc6-b2f4-63363d29d6bf)

**Comment by ltdrdata** [comment]
Connect the mediapipe facemesh preprocessor from cnet_aux directly and see the results.
MediaPipeDetectorProvider internally operates using that node.

**Comment by gay9cook** [comment]
Hello @ltdrdata , I am having the same issue, may I know which node is it? because I am new to ComfyUI, I have no idea which node is cnet_aux
![image](https://github.com/user-attachments/assets/d2bd18ba-31b1-48b2-8d18-f9d9757d7a42)
is it possible that you give me a screenshot for how the mediapipe workflow? Thanks a lot!

**Comment by ltdrdata** [comment]
> Hello @ltdrdata , I am having the same issue, may I know which node is it? because I am new to ComfyUI, I have no idea which node is cnet_aux ![image](https://private-user-images.githubusercontent.com/183334650/400208815-d2bd18ba-31b1-48b2-8d18-f9d9757d7a42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjQ0OTksIm5iZiI6MTczNjE2NDE5OSwicGF0aCI6Ii8xODMzMzQ2NTAvNDAwMjA4ODE1LWQyYmQxOGJhLTMxYjEtNDhiMi04ZDE4LWY5ZDk3NTdkN2E0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMTQ5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGI4YmIxNTI5ZDY0OWRhODMzZjRjYjM0YjRiZmY5YTVkNTU3NDNjYWIyNTk4OTkyOGRmN2E4OWJmZjcxZTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8wSxNOEQ9WK4KJd4aHvlGHAzXKtxiWxnFKeucBBjEdI) is it possible that you give me a screenshot for how the mediapipe workflow? Thanks a lot!

https://raw.githubusercontent.com/ltdrdata/ComfyUI-extension-tutorials/refs/heads/Main/ComfyUI-Impact-Pack/workflow/mediapipe-detector.png
